    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>Luna Shell — Desktop</title>\n"
    "  <link rel=\"stylesheet\" href=\"style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <!-- Background wallpaper layer -->\n"
    "  <div id=\"bg_layer\">\n"
    "    <div id=\"wallpaper\" class=\"night\">\n"
    "      <div id=\"wp_aurora1\"></div>\n"
    "      <div id=\"wp_aurora2\"></div>\n"
    "      <div id=\"wp_star1\" class=\"star\"></div>\n"
    "      <div id=\"wp_star2\" class=\"star\"></div>\n"
    "      <div id=\"wp_star3\" class=\"star\"></div>\n"
    "      <div id=\"wp_star4\" class=\"star\"></div>\n"
    "      <div id=\"wp_star5\" class=\"star\"></div>\n"
    "      <div id=\"wp_star6\" class=\"star\"></div>\n"
    "      <div id=\"wp_star7\" class=\"star\"></div>\n"
    "      <div id=\"wp_star8\" class=\"star\"></div>\n"
    "      <div id=\"wp_moon_halo\"></div>\n"
    "      <div id=\"wp_moon\"></div>\n"
    "    </div>\n"
    "  <!-- Desktop Widgets -->\n"
    "  <div id=\"widget_clock\" class=\"widget\">\n"
    "    <div id=\"wg_clock_view\">\n"
    "      <div id=\"wg_stopwatch_open\" class=\"wg_clock_icon luna_icon\" role=\"button\" tabindex=\"0\" aria-label=\"Open stopwatch\">&#xf2f2;</div>\n"
    "      <div id=\"wg_time\">23:00</div>\n"
    "      <div id=\"wg_date\">Tuesday, July 28</div>\n"
    "    </div>\n"
    "    <div id=\"wg_stopwatch_view\" class=\"hidden\">\n"
    "      <div id=\"wg_stopwatch_head\">\n"
    "        <div id=\"wg_stopwatch_back\" class=\"wg_clock_icon luna_icon\" role=\"button\" tabindex=\"0\" aria-label=\"Back to clock\">&#xf060;</div>\n"
    "        <span id=\"wg_stopwatch_title\">Stopwatch</span>\n"
    "        <span id=\"wg_stopwatch_state\">Ready</span>\n"
    "      </div>\n"
    "      <div id=\"wg_stopwatch_time\">00:00.0</div>\n"
    "      <div id=\"wg_stopwatch_actions\">\n"
    "        <div id=\"wg_stopwatch_toggle\" class=\"dlg_btn primary\" role=\"button\" tabindex=\"0\">Start</div>\n"
    "        <div id=\"wg_stopwatch_reset\" class=\"dlg_btn\" role=\"button\" tabindex=\"0\">Reset</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"widget_stats\" class=\"widget\">\n"
    "    <div class=\"st_row\">\n"
    "      <span class=\"st_label\">CPU Usage</span>\n"
    "      <span class=\"st_val\" id=\"st_cpu_val\">24%</span>\n"
    "    </div>\n"
    "    <div class=\"st_bar\"><div class=\"st_fill\" id=\"st_cpu_fill\" style=\"width: 24%;\"></div></div>\n"
    "\n"
    "    <div class=\"st_row\" style=\"margin-top: 12px;\">\n"
    "      <span class=\"st_label\">Memory</span>\n"
    "      <span class=\"st_val\" id=\"st_mem_val\">7.8 / 16 GB</span>\n"
    "    </div>\n"
    "    <div class=\"st_bar\"><div class=\"st_fill g_mem\" id=\"st_mem_fill\" style=\"width: 48%;\"></div></div>\n"
    "\n"
    "    <div class=\"st_row\" style=\"margin-top: 12px;\">\n"
    "      <span class=\"st_label\">Storage</span>\n"
    "      <span class=\"st_val\">142 / 512 GB</span>\n"
    "    </div>\n"
    "    <div class=\"st_bar\"><div class=\"st_fill g_disk\" style=\"width: 28%;\"></div></div>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"widget_weather\" class=\"widget\">\n"
    "    <div class=\"st_row\">\n"
    "      <span class=\"st_label\" id=\"wg_wx_city\">Weather</span>\n"
    "      <span class=\"st_val\" id=\"wg_wx_temp\">—</span>\n"
    "    </div>\n"
    "    <div id=\"wg_wx_main\">\n"
    "      <span class=\"luna_icon\" id=\"wg_wx_icon\">&#xf2c9;</span>\n"
    "      <span id=\"wg_wx_desc\">Fetching…</span>\n"
    "    </div>\n"
    "    <div id=\"wg_wx_forecast\">\n"
    "      <div id=\"wg_wf_0\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_1\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_2\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_3\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_4\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Dock -->\n"
    "  <div id=\"dock\">\n"
    "    <div class=\"dock_item\" id=\"dock_files\" role=\"button\" tabindex=\"0\" aria-label=\"Files\">\n"
    "      <div class=\"dock_icon g_files luna_icon\">&#xf07b;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_files\"></div>\n"
    "      <span class=\"dock_label\">Files</span>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_launchpad\" role=\"button\" tabindex=\"0\" aria-label=\"Applications\">\n"
    "      <div class=\"dock_icon g_launchpad luna_icon\">&#xf135;</div>\n"
    "      <div class=\"dock_dot spacer\"></div>\n"
    "      <span class=\"dock_label\">Apps</span>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_terminal\" role=\"button\" tabindex=\"0\" aria-label=\"Terminal\">\n"
    "      <div class=\"dock_icon g_terminal luna_icon\">&#xf120;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_terminal\"></div>\n"
    "      <span class=\"dock_label\">Terminal</span>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_browser\" role=\"button\" tabindex=\"0\" aria-label=\"Browser\">\n"
    "      <div class=\"dock_icon g_browser luna_icon\">&#xf0ac;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_browser\"></div>\n"
    "      <span class=\"dock_label\">Browser</span>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_editor\" role=\"button\" tabindex=\"0\" aria-label=\"Editor\">\n"
    "      <div class=\"dock_icon g_editor luna_icon\">&#xf15c;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_editor\"></div>\n"
    "      <span class=\"dock_label\">Editor</span>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_music\" role=\"button\" tabindex=\"0\" aria-label=\"Music\">\n"
    "      <div class=\"dock_icon g_music luna_icon\">&#xf001;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_music\"></div>\n"
    "      <span class=\"dock_label\">Music</span>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_settings\" role=\"button\" tabindex=\"0\" aria-label=\"Settings\">\n"
    "      <div class=\"dock_icon g_settings luna_icon\">&#xf013;</div>\n"
    "      <div class=\"dock_dot spacer\"></div>\n"
    "      <span class=\"dock_label\">Settings</span>\n"
    "    </div>\n"
    "    <div class=\"dock_sep\"></div>\n"
    "    <div class=\"dock_item\" id=\"dock_trash\" role=\"button\" tabindex=\"0\" aria-label=\"Trash\">\n"
    "      <div class=\"dock_icon g_trash luna_icon\">&#xf1f8;</div>\n"
    "      <div class=\"dock_dot spacer\"></div>\n"
    "      <span class=\"dock_label\">Trash</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Launchpad Overlay -->\n"
    "  <div id=\"launchpad\" class=\"hidden\">\n"
    "    <input type=\"text\" id=\"lp_search\" placeholder=\"Search applications\">\n"
    "    <div id=\"lp_grid\">\n"
    "      <div class=\"lp_app\" id=\"lp_files\">\n"
    "        <div class=\"lp_icon g_files luna_icon\">&#xf07b;</div>\n"
    "        <span class=\"lp_label\">Files</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_terminal\">\n"
    "        <div class=\"lp_icon g_terminal luna_icon\">&#xf120;</div>\n"
    "        <span class=\"lp_label\">Terminal</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_browser\">\n"
    "        <div class=\"lp_icon g_browser luna_icon\">&#xf0ac;</div>\n"
    "        <span class=\"lp_label\">Browser</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_editor\">\n"
    "        <div class=\"lp_icon g_editor luna_icon\">&#xf15c;</div>\n"
    "        <span class=\"lp_label\">Editor</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_music\">\n"
    "        <div class=\"lp_icon g_music luna_icon\">&#xf001;</div>\n"
    "        <span class=\"lp_label\">Music</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_settings\">\n"
    "        <div class=\"lp_icon g_settings luna_icon\">&#xf013;</div>\n"
    "        <span class=\"lp_label\">Settings</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_demo\">\n"
    "        <div class=\"lp_icon g_demo luna_icon\">&#xf121;</div>\n"
    "        <span class=\"lp_label\">GTK Demo</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_hello\">\n"
    "        <div class=\"lp_icon g_hello luna_icon\">&#xf118;</div>\n"
    "        <span class=\"lp_label\">Hello GTK</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_00\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_01\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_02\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_03\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_04\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_05\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_06\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_07\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_08\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_09\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_10\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_11\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_12\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_13\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_14\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_15\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_16\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_17\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_18\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_19\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_20\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_21\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_22\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_23\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_24\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_25\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_26\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_27\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_28\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_29\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_30\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_31\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_32\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_33\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_34\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_35\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_36\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_37\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_38\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_39\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_40\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_41\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_42\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_43\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_44\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_45\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_46\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app hidden\" id=\"lp_xdg_47\">\n"
    "        <div class=\"lp_icon luna_icon\">&#xf111;</div>\n"
    "        <span class=\"lp_label\">App</span>\n"
    "      </div>\n"
    "    </div>\n"
    "    <span id=\"lp_hint\">Press Esc to close Launchpad</span>\n"
    "  </div>\n"
    "\n"
    "  <!-- Confirmation Dialog Overlay -->\n"
    "  <div id=\"confirm_overlay\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"confirm_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"confirm_box\" class=\"alert_box dialog_window dialog_alert\" role=\"dialog\" aria-modal=\"false\" aria-labelledby=\"confirm_title\" aria-describedby=\"confirm_msg\">\n"
    "      <div class=\"tl tl_red\" id=\"ctl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"ctl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"ctl_max\"></div>\n"
    "      <div id=\"confirm_drag\"></div>\n"
    "      <div id=\"confirm_content\">\n"
    "        <div id=\"confirm_icon\" class=\"luna_icon\" aria-hidden=\"true\">&#xf011;</div>\n"
    "        <div id=\"confirm_copy\">\n"
    "          <div id=\"confirm_title\">Shut Down?</div>\n"
    "          <div id=\"confirm_msg\">Open applications will close. Save your work before continuing.</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"confirm_btns\">\n"
    "        <button id=\"confirm_cancel\" class=\"dlg_btn\">Cancel</button>\n"
    "        <button id=\"confirm_ok\" class=\"dlg_btn danger\">Shut Down</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Settings Sheet Window -->\n"
    "  <div id=\"settings_win\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"settings_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"settings_sheet\" class=\"sheet_box dialog_window\">\n"
    "      <div class=\"tl tl_red\" id=\"stl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"stl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"stl_max\"></div>\n"
    "      <div id=\"settings_drag\"></div>\n"
    "      <div id=\"settings_title\">System Settings</div>\n"
    "      <div id=\"settings_body\">\n"
    "        <div id=\"settings_sidebar\">\n"
    "          <div class=\"stab active\" id=\"stab_apps\" role=\"tab\" tabindex=\"0\"><span class=\"stab_icon luna_icon\">&#xf013;</span> Applications</div>\n"
    "          <div class=\"stab\" id=\"stab_disp\" role=\"tab\" tabindex=\"0\"><span class=\"stab_icon luna_icon\">&#xf108;</span> Appearance</div>\n"
    "          <div class=\"stab\" id=\"stab_language\" role=\"tab\" tabindex=\"0\"><span class=\"stab_icon luna_icon\">&#xf1ab;</span> Language</div>\n"
    "          <div class=\"stab\" id=\"stab_keyboard\" role=\"tab\" tabindex=\"0\"><span class=\"stab_icon luna_icon\">&#xf11c;</span> Keyboard</div>\n"
    "          <div class=\"stab\" id=\"stab_sound\" role=\"tab\" tabindex=\"0\"><span class=\"stab_icon luna_icon\">&#xf028;</span> Sound &amp; Display</div>\n"
    "          <div class=\"stab\" id=\"stab_wm\" role=\"tab\" tabindex=\"0\"><span class=\"stab_icon luna_icon\">&#xf2d0;</span> Windows</div>\n"
    "        </div>\n"
    "        <div id=\"settings_content\">\n"
    "          <!-- Apps Panel -->\n"
    "          <div id=\"settings_panel_apps\">\n"
    "            <span class=\"panel_heading\">Dock Applications</span>\n"
    "            <span class=\"pref_hint\">Show or hide Dock launchers and set the command (or .desktop file) each one opens.</span>\n"
    "            <div class=\"pref_row\">\n"
    "              <div class=\"dock_pref on\" id=\"dock_pref_files\" role=\"switch\" tabindex=\"0\"><div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div></div>\n"
    "              <span class=\"pref_label\">File Manager</span>\n"
    "              <input type=\"text\" id=\"pref_files\" class=\"pref_input\" value=\"pcmanfm\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <div class=\"dock_pref on\" id=\"dock_pref_terminal\" role=\"switch\" tabindex=\"0\"><div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div></div>\n"
    "              <span class=\"pref_label\">Terminal</span>\n"
    "              <input type=\"text\" id=\"pref_terminal\" class=\"pref_input\" value=\"sakura\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <div class=\"dock_pref on\" id=\"dock_pref_browser\" role=\"switch\" tabindex=\"0\"><div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div></div>\n"
    "              <span class=\"pref_label\">Web Browser</span>\n"
    "              <input type=\"text\" id=\"pref_browser\" class=\"pref_input\" value=\"firefox\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <div class=\"dock_pref on\" id=\"dock_pref_editor\" role=\"switch\" tabindex=\"0\"><div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div></div>\n"
    "              <span class=\"pref_label\">Text Editor</span>\n"
    "              <input type=\"text\" id=\"pref_editor\" class=\"pref_input\" value=\"luna-edit\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <div class=\"dock_pref on\" id=\"dock_pref_music\" role=\"switch\" tabindex=\"0\"><div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div></div>\n"
    "              <span class=\"pref_label\">Music Player</span>\n"
    "              <input type=\"text\" id=\"pref_music\" class=\"pref_input\" value=\"aplay+ui\">\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "          <!-- Appearance Panel -->\n"
    "          <div id=\"settings_panel_disp\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Desktop Skin</span>\n"
    "            <span class=\"pref_hint\">Choose a complete desktop look. Colors apply immediately; taskbar and deskbar skins also move the shell chrome.</span>\n"
    "            <div id=\"skin_cards\" role=\"radiogroup\" aria-label=\"Desktop skin\">\n"
    "              <div class=\"skin_card selected\" id=\"skin_0\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_0\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_0_name\">Luna Moonlight</span><span class=\"skin_desc\" id=\"skin_0_desc\">The built-in Luna desktop</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_1\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_1\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_1_name\">External skin</span><span class=\"skin_desc\" id=\"skin_1_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_2\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_2\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_2_name\">External skin</span><span class=\"skin_desc\" id=\"skin_2_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_3\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_3\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_3_name\">External skin</span><span class=\"skin_desc\" id=\"skin_3_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_4\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_4\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_4_name\">External skin</span><span class=\"skin_desc\" id=\"skin_4_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_5\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_5\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_5_name\">External skin</span><span class=\"skin_desc\" id=\"skin_5_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_6\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_6\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_6_name\">External skin</span><span class=\"skin_desc\" id=\"skin_6_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_7\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_7\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_7_name\">External skin</span><span class=\"skin_desc\" id=\"skin_7_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_8\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_0\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_8_name\">External skin</span><span class=\"skin_desc\" id=\"skin_8_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_9\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_1\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_9_name\">External skin</span><span class=\"skin_desc\" id=\"skin_9_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_10\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_2\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_10_name\">External skin</span><span class=\"skin_desc\" id=\"skin_10_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_11\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_0\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_11_name\">External skin</span><span class=\"skin_desc\" id=\"skin_11_desc\">Discovered automatically</span></div></div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"panel_heading\">Desktop Wallpaper</span>\n"
    "            <div id=\"wp_thumbs_row\" role=\"radiogroup\" aria-label=\"Desktop wallpaper\">\n"
    "              <div class=\"wp_thumb wp_t_night selected\" id=\"wp_night\" role=\"radio\" tabindex=\"0\"></div>\n"
    "              <div class=\"wp_thumb wp_t_ocean\" id=\"wp_ocean\" role=\"radio\" tabindex=\"0\"></div>\n"
    "              <div class=\"wp_thumb wp_t_forest\" id=\"wp_forest\" role=\"radio\" tabindex=\"0\"></div>\n"
    "              <div class=\"wp_thumb wp_t_sunset\" id=\"wp_sunset\" role=\"radio\" tabindex=\"0\"></div>\n"
    "            </div>\n"
    "            <div class=\"wp_label_row\">\n"
    "              <span class=\"wp_lbl\">Night Sky</span>\n"
    "              <span class=\"wp_lbl\">Deep Ocean</span>\n"
    "              <span class=\"wp_lbl\">Pine Forest</span>\n"
    "              <span class=\"wp_lbl\">Dusk Sunset</span>\n"
    "            </div>\n"
    "            <div class=\"wm_choice wallpaper_motion\" id=\"wm_wallpaper_motion\" role=\"switch\" tabindex=\"0\">Wallpaper motion · stars &amp; aurora</div>\n"
    "\n"
    "            <span class=\"panel_heading\" style=\"margin-top: 16px;\">Cursor Theme</span>\n"
    "            <div id=\"cur_thumbs_row\">\n"
    "              <div class=\"cur_card selected\" id=\"cur_aero\">\n"
    "                <div class=\"cur_preview cur_p_aero\"></div>\n"
    "                <span class=\"cur_name\">Aero Light</span>\n"
    "                <span class=\"cur_desc\">Modern translucent</span>\n"
    "              </div>\n"
    "              <div class=\"cur_card\" id=\"cur_miku\">\n"
    "                <div class=\"cur_preview cur_p_miku\"></div>\n"
    "                <span class=\"cur_name\">Cyan Magic</span>\n"
    "                <span class=\"cur_desc\">Vibrant glow</span>\n"
    "              </div>\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "          <!-- Language & region panel. Locale applies to apps launched after the change. -->\n"
    "          <div id=\"settings_panel_language\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Language &amp; Region</span>\n"
    "            <span class=\"pref_hint\">Choose the session language and regional format. New applications use it immediately; sign in again so every application inherits it.</span>\n"
    "            <span class=\"pref_section\">Application language and formats</span>\n"
    "            <div id=\"locale_cards\" class=\"option_card_grid\" role=\"radiogroup\" aria-label=\"Display language\">\n"
    "              <div class=\"option_card\" id=\"locale_ja\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">日本語</span><span class=\"option_card_desc\">日本 · ja_JP.UTF-8</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"locale_en\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">English</span><span class=\"option_card_desc\">United States · en_US.UTF-8</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"locale_c\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">English (portable)</span><span class=\"option_card_desc\">C.UTF-8 · always available</span>\n"
    "              </div>\n"
    "            </div>\n"
    "            <span class=\"pref_section\">Keyboard locks</span>\n"
    "            <div class=\"wm_pref system_pref\" id=\"sys_numlock\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">NumLock at sign-in</span><span class=\"wm_pref_desc\">Enable the numeric keypad now and restore it at the next Luna session.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <span class=\"settings_notice\">The physical NumLock key remains usable. CapsLock and ScrollLock are also synchronized with Wayland applications.</span>\n"
    "          </div>\n"
    "\n"
    "          <!-- Keyboard panel: selecting a card applies and saves immediately. -->\n"
    "          <div id=\"settings_panel_keyboard\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Keyboard Layout</span>\n"
    "            <span class=\"pref_hint\">Choose the physical key layout. The change applies immediately to every Wayland application.</span>\n"
    "            <span id=\"kb_current\" class=\"kb_current\">Current: System default</span>\n"
    "            <div id=\"kb_thumbs_row\" role=\"radiogroup\" aria-label=\"Keyboard layout\">\n"
    "              <div class=\"kb_card\" id=\"kb_jp\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">日本語 (JIS)</span><span class=\"kb_desc\">Japanese keyboard</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_jp_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">日本語 + US</span><span class=\"kb_desc\">Alt+Shift to switch</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">English (US)</span><span class=\"kb_desc\">US QWERTY</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_de_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">Deutsch + US</span><span class=\"kb_desc\">German / English</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_fr_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">Français + US</span><span class=\"kb_desc\">French / English</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_kr_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">한국어 + US</span><span class=\"kb_desc\">Korean / English</span></div>\n"
    "            </div>\n"
    "            <span class=\"kb_help\">複数配列では Alt + Shift で切り替えられます。日本語キーボードを固定する場合は「日本語 (JIS)」を選択してください。</span>\n"
    "            <span class=\"panel_heading\" style=\"margin-top: 18px;\">Desktop Shortcuts</span>\n"
    "            <span class=\"pref_hint\">Click a row, then press the new key. Esc cancels. Backspace clears. F4 is reserved for the file-manager terminal, so it is not used for Launchpad.</span>\n"
    "            <div class=\"shortcut_row\" id=\"shortcut_launchpad\" role=\"button\" tabindex=\"0\">\n"
    "              <div class=\"shortcut_text\"><span class=\"shortcut_name\">Launchpad</span><span class=\"shortcut_desc\">Show or hide the application launcher</span></div>\n"
    "              <span class=\"shortcut_key\" id=\"shortcut_launchpad_key\">Super</span>\n"
    "            </div>\n"
    "            <div class=\"shortcut_row\" id=\"shortcut_settings\" role=\"button\" tabindex=\"0\">\n"
    "              <div class=\"shortcut_text\"><span class=\"shortcut_name\">Settings</span><span class=\"shortcut_desc\">Open System Settings</span></div>\n"
    "              <span class=\"shortcut_key\" id=\"shortcut_settings_key\">Super+,</span>\n"
    "            </div>\n"
    "            <div class=\"shortcut_row\" id=\"shortcut_screenshot\" role=\"button\" tabindex=\"0\">\n"
    "              <div class=\"shortcut_text\"><span class=\"shortcut_name\">Screenshot</span><span class=\"shortcut_desc\">Capture the current screen</span></div>\n"
    "              <span class=\"shortcut_key\" id=\"shortcut_screenshot_key\">Print</span>\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "\n"
    "          <!-- Sound & display backends for Control Center sliders. -->\n"
    "          <div id=\"settings_panel_sound\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Sound</span>\n"
    "            <span class=\"pref_hint\">Choose how the Control Center volume slider talks to the system. Auto tries PipeWire, then PulseAudio, then ALSA.</span>\n"
    "            <span class=\"pref_section\">Volume backend</span>\n"
    "            <div id=\"audio_backend_cards\" class=\"option_card_grid\" role=\"radiogroup\" aria-label=\"Volume backend\">\n"
    "              <div class=\"option_card\" id=\"audio_auto\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">Auto</span><span class=\"option_card_desc\">PipeWire → Pulse → ALSA</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"audio_wpctl\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">PipeWire</span><span class=\"option_card_desc\">wpctl</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"audio_pactl\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">PulseAudio</span><span class=\"option_card_desc\">pactl</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"audio_alsa\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">ALSA</span><span class=\"option_card_desc\">amixer / alsamixer</span>\n"
    "              </div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"pref_section\">ALSA device</span>\n"
    "            <span class=\"pref_hint\">Used when the backend is ALSA (or Auto falls through to it). Card may be default, a number, or hw:N.</span>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\">Card</span>\n"
    "              <input type=\"text\" id=\"pref_alsa_card\" class=\"pref_input\" value=\"default\" placeholder=\"default or 0\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\">Control</span>\n"
    "              <input type=\"text\" id=\"pref_alsa_control\" class=\"pref_input\" value=\"Master\" placeholder=\"Master\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\"></span>\n"
    "              <div id=\"btn_open_alsamixer\" class=\"dlg_btn\">Open alsamixer</div>\n"
    "            </div>\n"
    "            <span id=\"audio_backend_status\" class=\"settings_notice\">Detecting audio tools…</span>\n"
    "\n"
    "            <span class=\"panel_heading\" style=\"margin-top: 16px;\">Display brightness</span>\n"
    "            <span class=\"pref_hint\">Choose how the Control Center brightness slider is applied.</span>\n"
    "            <span class=\"pref_section\">Brightness backend</span>\n"
    "            <div id=\"bright_backend_cards\" class=\"option_card_grid\" role=\"radiogroup\" aria-label=\"Brightness backend\">\n"
    "              <div class=\"option_card\" id=\"bright_auto\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">Auto</span><span class=\"option_card_desc\">Backlight → brightnessctl → xrandr</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"bright_sysfs\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">Backlight</span><span class=\"option_card_desc\">/sys/class/backlight</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"bright_brightnessctl\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">brightnessctl</span><span class=\"option_card_desc\">Userspace helper</span>\n"
    "              </div>\n"
    "              <div class=\"option_card\" id=\"bright_xrandr\" role=\"radio\" tabindex=\"0\">\n"
    "                <span class=\"option_card_name\">xrandr</span><span class=\"option_card_desc\">Software gamma</span>\n"
    "              </div>\n"
    "            </div>\n"
    "            <span id=\"bright_backend_status\" class=\"settings_notice\">Detecting brightness tools…</span>\n"
    "\n"
    "            <span class=\"panel_heading\" style=\"margin-top: 16px;\">Application display scale</span>\n"
    "            <span class=\"pref_hint\">Sliders apply to applications launched from Luna. Text scale is the usual control for Terminal and gedit; widget scale mainly affects file-manager chrome. Restart already-running apps to see the new size.</span>\n"
    "            <div class=\"scale_pref\">\n"
    "              <div class=\"scale_pref_head\">\n"
    "                <span class=\"pref_section\">Text scale (GDK_DPI_SCALE)</span>\n"
    "                <span class=\"scale_val\" id=\"scale_dpi_val\">1.00</span>\n"
    "              </div>\n"
    "              <span class=\"pref_hint\">Makes GTK text larger or smaller without doubling window buffers.</span>\n"
    "              <div class=\"cc_track scale_track\" id=\"scale_dpi_track\">\n"
    "                <div class=\"cc_fill\" id=\"scale_dpi_fill\"></div>\n"
    "                <div class=\"cc_thumb\" id=\"scale_dpi_thumb\"></div>\n"
    "              </div>\n"
    "            </div>\n"
    "            <div class=\"scale_pref\">\n"
    "              <div class=\"scale_pref_head\">\n"
    "                <span class=\"pref_section\">Widget scale (GDK_SCALE)</span>\n"
    "                <span class=\"scale_val\" id=\"scale_gdk_val\">0.80</span>\n"
    "              </div>\n"
    "              <span class=\"pref_hint\">Overall GTK widget and icon size. Keep near 0.8 if pcmanfm already looks right. Integer 2× submits a HiDPI buffer.</span>\n"
    "              <div class=\"cc_track scale_track\" id=\"scale_gdk_track\">\n"
    "                <div class=\"cc_fill\" id=\"scale_gdk_fill\"></div>\n"
    "                <div class=\"cc_thumb\" id=\"scale_gdk_thumb\"></div>\n"
    "              </div>\n"
    "            </div>\n"
    "            <div class=\"scale_pref\">\n"
    "              <div class=\"scale_pref_head\">\n"
    "                <span class=\"pref_section\">Qt scale (QT_SCALE_FACTOR)</span>\n"
    "                <span class=\"scale_val\" id=\"scale_qt_val\">1.00</span>\n"
    "              </div>\n"
    "              <div class=\"cc_track scale_track\" id=\"scale_qt_track\">\n"
    "                <div class=\"cc_fill\" id=\"scale_qt_fill\"></div>\n"
    "                <div class=\"cc_thumb\" id=\"scale_qt_thumb\"></div>\n"
    "              </div>\n"
    "            </div>\n"
    "            <div class=\"scale_pref\">\n"
    "              <div class=\"scale_pref_head\">\n"
    "                <span class=\"pref_section\">Cursor size (XCURSOR_SIZE)</span>\n"
    "                <span class=\"scale_val\" id=\"scale_cur_val\">24</span>\n"
    "              </div>\n"
    "              <div class=\"cc_track scale_track\" id=\"scale_cur_track\">\n"
    "                <div class=\"cc_fill\" id=\"scale_cur_fill\"></div>\n"
    "                <div class=\"cc_thumb\" id=\"scale_cur_thumb\"></div>\n"
    "              </div>\n"
    "            </div>\n"
    "            <span class=\"settings_notice\">Already-running applications keep their old scale until restarted. LUNA_GDK_SCALE / LUNA_GDK_DPI_SCALE / LUNA_QT_SCALE_FACTOR / LUNA_XCURSOR_SIZE still override these when set.</span>\n"
    "\n"
    "          </div>\n"
    "\n"
    "          <!-- Window-management panel: lightweight compositor settings. -->\n"
    "          <div id=\"settings_panel_wm\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Window Management</span>\n"
    "            <span class=\"pref_hint\">Changes apply immediately and are saved with the other desktop settings.</span>\n"
    "\n"
    "            <div class=\"wm_pref\" id=\"wm_snap\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Magnetic snapping</span><span class=\"wm_pref_desc\">Stick windows to the screen and to other windows while dragging.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_tile\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Tile at screen edge</span><span class=\"wm_pref_desc\">Drop against the left or right edge to fill that half of the screen.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_top_maximize\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Maximize at top edge</span><span class=\"wm_pref_desc\">Use the classic behavior when dragging a window to the top edge.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_double_click\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Double-click title bar</span><span class=\"wm_pref_desc\">Maximize or restore the active window.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_classic_titlebar\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Classic title bars</span><span class=\"wm_pref_desc\">Use the original solid bar and traffic-light controls for server-decorated windows.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_shortcuts\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Super-key shortcuts</span><span class=\"wm_pref_desc\">Arrows tile and restore; Super+D shows the desktop.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"pref_section\">Tiled window gap</span>\n"
    "            <div class=\"wm_choice_row\">\n"
    "              <div class=\"wm_choice\" id=\"wm_gap_0\" role=\"radio\" tabindex=\"0\">None</div>\n"
    "              <div class=\"wm_choice\" id=\"wm_gap_8\" role=\"radio\" tabindex=\"0\">Compact</div>\n"
    "              <div class=\"wm_choice\" id=\"wm_gap_16\" role=\"radio\" tabindex=\"0\">Comfortable</div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"pref_section\">Desktop behavior</span>\n"
    "            <div class=\"wm_pref\" id=\"wm_dock\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Show dock</span><span class=\"wm_pref_desc\">Display the floating application dock at the bottom of the screen.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_widgets\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Show desktop widgets</span><span class=\"wm_pref_desc\">Display clock, system statistics, and weather cards on the desktop.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_dock_mag\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Dock hover animation</span><span class=\"wm_pref_desc\">Lift only the pointed icon using the skin stylesheet.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_restore\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Restore previous session</span><span class=\"wm_pref_desc\">Reopen applications and restore window state after login.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"settings_btns\">\n"
    "        <button class=\"dlg_btn\" id=\"settings_cancel\">Cancel</button>\n"
    "        <button class=\"dlg_btn primary\" id=\"settings_ok\">Apply Changes</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- About Box Window -->\n"
    "  <div id=\"about_win\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"about_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"about_box\" class=\"sheet_box about_box dialog_window\">\n"
    "      <div class=\"tl tl_red\" id=\"tl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"tl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"tl_max\"></div>\n"
    "      <div id=\"about_drag\"></div>\n"
    "      <div id=\"about_content\">\n"
    "        <div id=\"about_icon\"><div class=\"luna_icon\" aria-hidden=\"true\">&#xf186;</div></div>\n"
    "        <div id=\"about_title\">Luna OS</div>\n"
    "        <div id=\"about_ver\"><span class=\"about_ver_dot\"></span>Version 1.0 · Moonlight Edition</div>\n"
    "        <div id=\"about_sep\"></div>\n"
    "        <div id=\"about_grid\">\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf085;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Shell</span>\n"
    "              <span class=\"spec_value\" id=\"about_shell\">Luna Shell 1.0</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf03e;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Compositor</span>\n"
    "              <span class=\"spec_value\" id=\"about_comp\">Luna UI Layer</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_brand\">&#xf17c;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Kernel</span>\n"
    "              <span class=\"spec_value\" id=\"about_kernel\">6.12.0-luna</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf1c0;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Memory</span>\n"
    "              <span class=\"spec_value\" id=\"about_mem\">16.0 GB DDR5</span>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Network details (right-click a Wi-Fi / Ethernet row) -->\n"
    "  <div id=\"net_detail_win\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"net_detail_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"net_detail_box\" class=\"sheet_box about_box dialog_window\">\n"
    "      <div class=\"tl tl_red\" id=\"ntl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"ntl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"ntl_max\"></div>\n"
    "      <div id=\"net_detail_drag\"></div>\n"
    "      <div id=\"net_detail_content\">\n"
    "        <div id=\"net_detail_icon\"><div class=\"luna_icon\" aria-hidden=\"true\">&#xf1eb;</div></div>\n"
    "        <div id=\"net_detail_title\">Network</div>\n"
    "        <div id=\"net_detail_ver\"><span class=\"about_ver_dot\"></span><span id=\"net_detail_status\">—</span></div>\n"
    "        <div id=\"net_detail_sep\"></div>\n"
    "        <div id=\"net_detail_grid\">\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf0ac;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Interface</span>\n"
    "              <span class=\"spec_value\" id=\"nd_iface\">—</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf1eb;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">IPv4</span>\n"
    "              <span class=\"spec_value\" id=\"nd_ipv4\">—</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf0c1;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">IPv6</span>\n"
    "              <span class=\"spec_value\" id=\"nd_ipv6\">—</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf074;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Gateway</span>\n"
    "              <span class=\"spec_value\" id=\"nd_gateway\">—</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf0e8;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">DNS</span>\n"
    "              <span class=\"spec_value\" id=\"nd_dns\">—</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf2db;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">MAC / Extra</span>\n"
    "              <span class=\"spec_value\" id=\"nd_extra\">—</span>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"net_detail_btns\">\n"
    "        <button class=\"dlg_btn\" id=\"net_detail_close\">Close</button>\n"
    "        <button class=\"dlg_btn primary\" id=\"net_detail_action\">Disconnect</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Alarm ring overlay -->\n"
    "  <div id=\"alarm_ring\" class=\"modal_sheet hidden\">\n"
    "    <div id=\"alarm_ring_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"alarm_ring_card\" role=\"dialog\" aria-labelledby=\"alarm_ring_time\">\n"
    "      <div id=\"alarm_ring_orb\" class=\"luna_icon\">&#xf0f3;</div>\n"
    "      <div id=\"alarm_ring_time\">07:30</div>\n"
    "      <div id=\"alarm_ring_label\">Alarm</div>\n"
    "      <div id=\"alarm_ring_when\">Monday · August 17</div>\n"
    "      <div id=\"alarm_ring_actions\">\n"
    "        <div id=\"alarm_snooze\" class=\"dlg_btn\">Snooze 5 min</div>\n"
    "        <div id=\"alarm_dismiss\" class=\"dlg_btn primary\">Dismiss</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Top Menu Bar -->\n"
    "  <div id=\"menubar\">\n"
    "    <div id=\"mb_left\">\n"
    "      <div id=\"mb_logo\" class=\"mb_item\" aria-label=\"Luna menu\"><div id=\"mb_logo_glyph\" class=\"luna_icon\" aria-hidden=\"true\">&#xf186;</div></div>\n"
    "      <div id=\"mb_app\" class=\"mb_item mb_app_name\">Luna Shell</div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"mb_center\">\n"
    "      <div id=\"win_list\">\n"
    "        <div id=\"win_0\" class=\"win_item active\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Terminal</span></div>\n"
    "        <div id=\"win_1\" class=\"win_item\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Files</span></div>\n"
    "        <div id=\"win_2\" class=\"win_item minimized\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Editor</span></div>\n"
    "        <div id=\"win_3\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_4\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_5\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_6\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_7\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_8\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_9\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_10\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_11\" class=\"win_item hidden\"><span class=\"win_glyph luna_icon\"></span><span class=\"win_label\">Window</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"mb_right\">\n"
    "      <div id=\"tray_area\">\n"
    "        <div id=\"tray_0\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_1\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_2\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_3\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_4\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_5\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_6\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "        <div id=\"tray_7\" class=\"tray_item hidden\"><span class=\"tray_glyph luna_icon\"></span></div>\n"
    "      </div>\n"
    "      <div id=\"mb_clip\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf0ea;</span></div>\n"
    "      <div id=\"mb_wifi\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf1eb;</span></div>\n"
    "      <div id=\"mb_bat\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf240;</span> 98%</div>\n"
    "      <div id=\"mb_cc\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf1de;</span></div>\n"
    "      <div id=\"mb_weather\" class=\"mb_item mb_status\" title=\"Weather\">\n"
    "        <span class=\"luna_icon\" id=\"mb_weather_icon\">&#xf2c9;</span>\n"
    "        <span id=\"mb_weather_temp\">—</span>\n"
    "      </div>\n"
    "      <div id=\"mb_clock\" class=\"mb_item\">Tue Jul 28  23:00</div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Window actions, opened by a title-bar or window-list right click. -->\n"
    "  <div id=\"win_menu\" class=\"menu_panel hidden\">\n"
    "    <span id=\"win_menu_title\" class=\"menu_section_label\">Window</span>\n"
    "    <div id=\"wm_activate\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf2d0;</span><span class=\"mi_label\">Activate</span></div>\n"
    "    <div id=\"wm_minimize\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf2d1;</span><span class=\"mi_label\">Minimize</span></div>\n"
    "    <div id=\"wm_maximize\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf2d0;</span><span class=\"mi_label\">Maximize</span></div>\n"
    "    <div id=\"wm_fullscreen\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf065;</span><span class=\"mi_label\">Fullscreen</span></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wm_tile_left\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf053;</span><span class=\"mi_label\">Tile Left</span></div>\n"
    "    <div id=\"wm_tile_right\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf054;</span><span class=\"mi_label\">Tile Right</span></div>\n"
    "    <div id=\"wm_center\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf192;</span><span class=\"mi_label\">Center</span></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wm_close\" class=\"menu_item mi_destructive\"><span class=\"mi_sym luna_icon\">&#xf00d;</span><span class=\"mi_label\">Close</span></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Alt+Tab switcher.  Keep one element per MAX_SWITCHER_SLOTS. -->\n"
    "  <div id=\"switcher\" class=\"switcher_overlay hidden\">\n"
    "    <div id=\"switcher_strip\">\n"
    "      <div id=\"sw_0\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_1\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_2\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_3\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_4\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_5\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_6\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_7\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_8\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_9\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_10\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_11\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Wi-Fi menu (backed by ConnMan, with NetworkManager fallback) -->\n"
    "  <div id=\"wifi_menu\" class=\"menu_panel hidden\">\n"
    "    <div id=\"wifi_head\">\n"
    "      <span id=\"wifi_title\">Wi-Fi</span>\n"
    "      <div class=\"cc_toggle\" id=\"wifi_power\"><div class=\"cc_knob\"></div></div>\n"
    "    </div>\n"
    "    <span id=\"wifi_status\">Checking network service...</span>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wifi_0\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_1\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_2\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_3\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_4\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_5\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_6\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_7\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_credentials\" class=\"hidden\">\n"
    "      <span id=\"wifi_selected\">Connect to network</span>\n"
    "      <input type=\"password\" id=\"wifi_password\" placeholder=\"Password (leave blank if saved/open)\">\n"
    "      <div id=\"wifi_connect\" class=\"dlg_btn primary\">Connect</div>\n"
    "    </div>\n"
    "    <div id=\"net_tip\" class=\"net_tip hidden\">\n"
    "      <span id=\"net_tip_line\">—</span>\n"
    "    </div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wifi_scan\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf021;</span><span class=\"mi_label\">Scan for Networks</span></div>\n"
    "    <div class=\"menu_sep\" id=\"eth_sep\"></div>\n"
    "    <span class=\"menu_section_label\" id=\"eth_section\">Ethernet</span>\n"
    "    <span id=\"eth_status\">Checking wired interfaces...</span>\n"
    "    <div id=\"eth_0\" class=\"menu_item eth_link hidden\"><span class=\"mi_sym luna_icon\">&#xf6ff;</span><span class=\"mi_label\">Ethernet</span><span class=\"eth_state\"></span></div>\n"
    "    <div id=\"eth_1\" class=\"menu_item eth_link hidden\"><span class=\"mi_sym luna_icon\">&#xf6ff;</span><span class=\"mi_label\">Ethernet</span><span class=\"eth_state\"></span></div>\n"
    "    <div id=\"eth_2\" class=\"menu_item eth_link hidden\"><span class=\"mi_sym luna_icon\">&#xf6ff;</span><span class=\"mi_label\">Ethernet</span><span class=\"eth_state\"></span></div>\n"
    "    <div id=\"eth_3\" class=\"menu_item eth_link hidden\"><span class=\"mi_sym luna_icon\">&#xf6ff;</span><span class=\"mi_label\">Ethernet</span><span class=\"eth_state\"></span></div>\n"
    "  </div>\n"
    "\n"
    "\n"
    "  <!-- Bluetooth menu (backed by bluetoothctl / ConnMan) -->\n"
    "  <div id=\"bt_menu\" class=\"menu_panel hidden\">\n"
    "    <div id=\"bt_head\">\n"
    "      <span id=\"bt_title\">Bluetooth</span>\n"
    "      <div class=\"cc_toggle\" id=\"bt_power\"><div class=\"cc_knob\"></div></div>\n"
    "    </div>\n"
    "    <span id=\"bt_status\">Checking Bluetooth service...</span>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"bt_0\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_1\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_2\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_3\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_4\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_5\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_6\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div id=\"bt_7\" class=\"menu_item bt_device hidden\"><span class=\"mi_sym luna_icon\">&#xf293;</span><span class=\"mi_label\">Device</span><span class=\"bt_state\"></span></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"bt_scan\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf021;</span><span class=\"mi_label\">Scan for Devices</span></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Luna Dropdown Menu -->\n"
    "  <div id=\"luna_menu\" class=\"menu_panel hidden\">\n"
    "    <span class=\"menu_section_label\">System</span>\n"
    "    <div class=\"menu_item\" id=\"mi_about\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf186;</span>\n"
    "      <span class=\"mi_label\">About This PC...</span>\n"
    "    </div>\n"
    "    <div class=\"menu_item\" id=\"mi_settings\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf013;</span>\n"
    "      <span class=\"mi_label\">System Settings...</span>\n"
    "      <span class=\"mi_key\">⌘,</span>\n"
    "    </div>\n"
    "    <div class=\"menu_item\" id=\"mi_launchpad\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf135;</span>\n"
    "      <span class=\"mi_label\">Launchpad</span>\n"
    "      <span class=\"mi_key\">F4</span>\n"
    "    </div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div class=\"menu_item\" id=\"mi_restart\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf021;</span>\n"
    "      <span class=\"mi_label\">Restart...</span>\n"
    "    </div>\n"
    "    <div class=\"menu_item mi_destructive\" id=\"mi_shutdown\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf011;</span>\n"
    "      <span class=\"mi_label\">Shut Down...</span>\n"
    "    </div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div class=\"menu_item mi_destructive\" id=\"mi_logout\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf08b;</span>\n"
    "      <span class=\"mi_label\">Log Out...</span>\n"
    "      <span class=\"mi_key\">⇧⌘Q</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Clipboard history.  The shell populates and wires these items in C. -->\n"
    "  <div id=\"clip_menu\" class=\"menu_panel hidden\">\n"
    "    <div class=\"menu_section_label\">Clipboard</div>\n"
    "    <div id=\"clip_empty\" class=\"clip_empty\">No recent copies</div>\n"
    "    <div id=\"clip_0\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">1</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_1\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">2</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_2\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">3</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_3\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">4</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_4\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">5</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_5\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">6</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_6\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">7</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_7\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">8</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"clip_clear\" class=\"menu_item mi_destructive\"><div class=\"mi_sym\">✕</div><div class=\"mi_label\">Clear History</div></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Control Center -->\n"
    "  <div id=\"control_center\" class=\"menu_panel hidden\">\n"
    "    <div class=\"cc_row\">\n"
    "      <div class=\"cc_cell\">\n"
    "        <div class=\"cc_toggle on\" id=\"cc_wifi\"><div class=\"cc_knob\"></div></div>\n"
    "        <span class=\"cc_label\">Wi-Fi</span>\n"
    "      </div>\n"
    "      <div class=\"cc_cell\">\n"
    "        <div class=\"cc_toggle on\" id=\"cc_bt\"><div class=\"cc_knob\"></div></div>\n"
    "        <span class=\"cc_label\" id=\"cc_bt_open\">Bluetooth</span>\n"
    "      </div>\n"
    "      <div class=\"cc_cell\">\n"
    "        <div class=\"cc_toggle\" id=\"cc_night\"><div class=\"cc_knob\"></div></div>\n"
    "        <span class=\"cc_label\">Night Shift</span>\n"
    "      </div>\n"
    "    </div>\n"
    "    <span class=\"cc_section\">Display & Sound</span>\n"
    "    <div class=\"cc_track\" id=\"bright_track\">\n"
    "      <div class=\"cc_fill\" id=\"bright_fill\"></div>\n"
    "      <div class=\"cc_thumb\" id=\"bright_thumb\"></div>\n"
    "    </div>\n"
    "    <div class=\"cc_track\" id=\"vol_track\">\n"
    "      <div class=\"cc_fill\" id=\"vol_fill\"></div>\n"
    "      <div class=\"cc_thumb\" id=\"vol_thumb\"></div>\n"
    "    </div>\n"
    "    <span class=\"cc_section\">System Performance</span>\n"
    "    <div class=\"cc_stat_row\">\n"
    "      <span class=\"cc_stat_label\">CPU</span>\n"
    "      <div class=\"cc_bar\"><div class=\"cc_bar_fill\" id=\"cc_cpu_fill\" style=\"width: 24%;\"></div></div>\n"
    "    </div>\n"
    "    <div class=\"cc_stat_row\">\n"
    "      <span class=\"cc_stat_label\">RAM</span>\n"
    "      <div class=\"cc_bar\"><div class=\"cc_bar_fill\" id=\"cc_mem_fill\" style=\"width: 48%;\"></div></div>\n"
    "    </div>\n"
    "    <span class=\"cc_section\">Notifications</span>\n"
    "    <div id=\"notify_empty\" class=\"cc_stat_row\"><span class=\"cc_stat_label\">No recent notifications</span></div>\n"
    "    <div id=\"notify_0\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_0_text\">—</span></div>\n"
    "    <div id=\"notify_1\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_1_text\">—</span></div>\n"
    "    <div id=\"notify_2\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_2_text\">—</span></div>\n"
    "    <div id=\"notify_3\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_3_text\">—</span></div>\n"
    "    <div id=\"notify_4\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_4_text\">—</span></div>\n"
    "    <div id=\"notify_5\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_5_text\">—</span></div>\n"
    "    <div id=\"notify_6\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_6_text\">—</span></div>\n"
    "    <div id=\"notify_7\" class=\"cc_stat_row hidden\"><span class=\"cc_stat_label\" id=\"notify_7_text\">—</span></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Calendar popover (opened from menubar clock / desktop date) -->\n"
    "  <div id=\"calendar_menu\" class=\"menu_panel hidden\">\n"
    "    <div id=\"cal_head\">\n"
    "      <div id=\"cal_prev\" class=\"cal_nav luna_icon\" role=\"button\" tabindex=\"0\">&#xf053;</div>\n"
    "      <span id=\"cal_month_label\">August 2026</span>\n"
    "      <div id=\"cal_next\" class=\"cal_nav luna_icon\" role=\"button\" tabindex=\"0\">&#xf054;</div>\n"
    "    </div>\n"
    "    <div id=\"cal_weekdays\">\n"
    "      <span class=\"cal_wd\">Su</span><span class=\"cal_wd\">Mo</span><span class=\"cal_wd\">Tu</span><span class=\"cal_wd\">We</span>\n"
    "      <span class=\"cal_wd\">Th</span><span class=\"cal_wd\">Fr</span><span class=\"cal_wd\">Sa</span>\n"
    "    </div>\n"
    "    <div id=\"cal_grid\">\n"
    "      <div id=\"cal_d0\" class=\"cal_day\"></div><div id=\"cal_d1\" class=\"cal_day\"></div><div id=\"cal_d2\" class=\"cal_day\"></div><div id=\"cal_d3\" class=\"cal_day\"></div><div id=\"cal_d4\" class=\"cal_day\"></div><div id=\"cal_d5\" class=\"cal_day\"></div><div id=\"cal_d6\" class=\"cal_day\"></div>\n"
    "      <div id=\"cal_d7\" class=\"cal_day\"></div><div id=\"cal_d8\" class=\"cal_day\"></div><div id=\"cal_d9\" class=\"cal_day\"></div><div id=\"cal_d10\" class=\"cal_day\"></div><div id=\"cal_d11\" class=\"cal_day\"></div><div id=\"cal_d12\" class=\"cal_day\"></div><div id=\"cal_d13\" class=\"cal_day\"></div>\n"
    "      <div id=\"cal_d14\" class=\"cal_day\"></div><div id=\"cal_d15\" class=\"cal_day\"></div><div id=\"cal_d16\" class=\"cal_day\"></div><div id=\"cal_d17\" class=\"cal_day\"></div><div id=\"cal_d18\" class=\"cal_day\"></div><div id=\"cal_d19\" class=\"cal_day\"></div><div id=\"cal_d20\" class=\"cal_day\"></div>\n"
    "      <div id=\"cal_d21\" class=\"cal_day\"></div><div id=\"cal_d22\" class=\"cal_day\"></div><div id=\"cal_d23\" class=\"cal_day\"></div><div id=\"cal_d24\" class=\"cal_day\"></div><div id=\"cal_d25\" class=\"cal_day\"></div><div id=\"cal_d26\" class=\"cal_day\"></div><div id=\"cal_d27\" class=\"cal_day\"></div>\n"
    "      <div id=\"cal_d28\" class=\"cal_day\"></div><div id=\"cal_d29\" class=\"cal_day\"></div><div id=\"cal_d30\" class=\"cal_day\"></div><div id=\"cal_d31\" class=\"cal_day\"></div><div id=\"cal_d32\" class=\"cal_day\"></div><div id=\"cal_d33\" class=\"cal_day\"></div><div id=\"cal_d34\" class=\"cal_day\"></div>\n"
    "      <div id=\"cal_d35\" class=\"cal_day\"></div><div id=\"cal_d36\" class=\"cal_day\"></div><div id=\"cal_d37\" class=\"cal_day\"></div><div id=\"cal_d38\" class=\"cal_day\"></div><div id=\"cal_d39\" class=\"cal_day\"></div><div id=\"cal_d40\" class=\"cal_day\"></div><div id=\"cal_d41\" class=\"cal_day\"></div>\n"
    "    </div>\n"
    "    <div id=\"cal_today_btn\" class=\"dlg_btn\">Today</div>\n"
    "    <div id=\"cal_alarm\">\n"
    "      <div id=\"cal_alarm_head\">\n"
    "        <span id=\"cal_alarm_bell\" class=\"luna_icon\">&#xf0f3;</span>\n"
    "        <span id=\"cal_alarm_date\">Pick a day</span>\n"
    "        <span id=\"cal_alarm_count\">No alarms</span>\n"
    "      </div>\n"
    "      <div id=\"cal_alarm_list\">\n"
    "        <div id=\"cal_al0\" class=\"cal_al_row hidden\">\n"
    "          <span class=\"cal_al_time\">07:30</span>\n"
    "          <span class=\"cal_al_label\">Alarm</span>\n"
    "          <span class=\"cal_al_repeat\">Once</span>\n"
    "          <div id=\"cal_al0_del\" class=\"cal_al_del luna_icon\" role=\"button\" tabindex=\"0\">&#xf00d;</div>\n"
    "        </div>\n"
    "        <div id=\"cal_al1\" class=\"cal_al_row hidden\">\n"
    "          <span class=\"cal_al_time\">07:30</span>\n"
    "          <span class=\"cal_al_label\">Alarm</span>\n"
    "          <span class=\"cal_al_repeat\">Once</span>\n"
    "          <div id=\"cal_al1_del\" class=\"cal_al_del luna_icon\" role=\"button\" tabindex=\"0\">&#xf00d;</div>\n"
    "        </div>\n"
    "        <div id=\"cal_al2\" class=\"cal_al_row hidden\">\n"
    "          <span class=\"cal_al_time\">07:30</span>\n"
    "          <span class=\"cal_al_label\">Alarm</span>\n"
    "          <span class=\"cal_al_repeat\">Once</span>\n"
    "          <div id=\"cal_al2_del\" class=\"cal_al_del luna_icon\" role=\"button\" tabindex=\"0\">&#xf00d;</div>\n"
    "        </div>\n"
    "        <div id=\"cal_al3\" class=\"cal_al_row hidden\">\n"
    "          <span class=\"cal_al_time\">07:30</span>\n"
    "          <span class=\"cal_al_label\">Alarm</span>\n"
    "          <span class=\"cal_al_repeat\">Once</span>\n"
    "          <div id=\"cal_al3_del\" class=\"cal_al_del luna_icon\" role=\"button\" tabindex=\"0\">&#xf00d;</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"cal_alarm_empty\">No alarms this day</div>\n"
    "      <div id=\"cal_alarm_composer\">\n"
    "        <input type=\"text\" id=\"cal_alarm_time\" placeholder=\"07:30\">\n"
    "        <input type=\"text\" id=\"cal_alarm_note\" placeholder=\"Label\">\n"
    "        <div id=\"cal_alarm_repeat\" class=\"cal_chip\" role=\"button\" tabindex=\"0\">Once</div>\n"
    "        <div id=\"cal_alarm_add\" class=\"dlg_btn primary\">Set</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Weather popover (Open-Meteo; mirrors qberry-weather.js) -->\n"
    "  <div id=\"weather_menu\" class=\"menu_panel hidden\">\n"
    "    <div id=\"weather_search\">\n"
    "      <input type=\"text\" id=\"weather_city_input\" placeholder=\"City (e.g. Tokyo)\">\n"
    "      <div id=\"weather_go\" class=\"dlg_btn primary\">Go</div>\n"
    "    </div>\n"
    "    <div id=\"weather_body\">\n"
    "      <span id=\"weather_hint\">Locating…</span>\n"
    "      <div id=\"weather_content\" class=\"hidden\">\n"
    "        <div id=\"weather_city_label\">—</div>\n"
    "        <div id=\"weather_main\">\n"
    "          <span class=\"luna_icon\" id=\"weather_icon\">&#xf185;</span>\n"
    "          <div>\n"
    "            <div id=\"weather_temp\">—°C</div>\n"
    "            <div id=\"weather_desc\">—</div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div id=\"weather_stats_row\">\n"
    "          <span id=\"weather_feels\">Feels —</span>\n"
    "          <span id=\"weather_hum\">—%</span>\n"
    "          <span id=\"weather_wind\">— km/h</span>\n"
    "        </div>\n"
    "        <div id=\"weather_forecast\">\n"
    "          <div id=\"wf_0\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_1\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_2\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_3\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_4\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <span id=\"weather_error\" class=\"hidden\">Weather unavailable</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Notification Toast -->\n"
    "  <div id=\"toast\" class=\"hidden\">\n"
    "    <div id=\"toast_icon\" class=\"luna_icon\">&#xf186;</div>\n"
    "    <div id=\"toast_body\">\n"
    "      <div id=\"toast_title\">System Notification</div>\n"
    "      <div id=\"toast_msg\">Luna UI Engine updated to v2.0</div>\n"
    "    </div>\n"
    "    <div id=\"toast_close\">✕</div>\n"
    "  </div>\n"
    "</body>\n"
    "</html>\n"
