    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>Luna Shell — Desktop</title>\n"
    "  <link rel=\"stylesheet\" href=\"luna-shell.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <!-- Background wallpaper layer -->\n"
    "  <div id=\"bg_layer\">\n"
    "    <div id=\"wallpaper\" class=\"night\">\n"
    "      <div id=\"wp_aurora1\"></div>\n"
    "      <div id=\"wp_aurora2\"></div>\n"
    "      <div id=\"wp_star1\" class=\"star\"></div>\n"
    "      <div id=\"wp_star2\" class=\"star\"></div>\n"
    "      <div id=\"wp_star3\" class=\"star\"></div>\n"
    "      <div id=\"wp_star4\" class=\"star\"></div>\n"
    "      <div id=\"wp_star5\" class=\"star\"></div>\n"
    "      <div id=\"wp_star6\" class=\"star\"></div>\n"
    "      <div id=\"wp_star7\" class=\"star\"></div>\n"
    "      <div id=\"wp_star8\" class=\"star\"></div>\n"
    "      <div id=\"wp_moon_halo\"></div>\n"
    "      <div id=\"wp_moon\"></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Top Menu Bar -->\n"
    "  <div id=\"menubar\">\n"
    "    <div id=\"mb_left\">\n"
    "      <div id=\"mb_logo\" class=\"mb_item\" aria-label=\"Luna menu\"><div id=\"mb_logo_glyph\" class=\"luna_icon\" aria-hidden=\"true\">&#xf186;</div></div>\n"
    "      <div id=\"mb_app\" class=\"mb_item mb_app_name\">Luna Shell</div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"mb_center\">\n"
    "      <div id=\"win_list\">\n"
    "        <div id=\"win_0\" class=\"win_item active\"><span class=\"win_label\">Terminal</span></div>\n"
    "        <div id=\"win_1\" class=\"win_item\"><span class=\"win_label\">Files</span></div>\n"
    "        <div id=\"win_2\" class=\"win_item minimized\"><span class=\"win_label\">Editor</span></div>\n"
    "        <div id=\"win_3\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_4\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_5\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_6\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_7\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_8\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_9\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_10\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "        <div id=\"win_11\" class=\"win_item hidden\"><span class=\"win_label\">Window</span></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"mb_right\">\n"
    "      <div id=\"tray_area\">\n"
    "        <div id=\"tray_0\" class=\"tray_item icon_terminal\"><span class=\"tray_glyph luna_icon\">&#xf120;</span></div>\n"
    "        <div id=\"tray_1\" class=\"tray_item icon_browser\"><span class=\"tray_glyph luna_icon\">&#xf0ac;</span></div>\n"
    "        <div id=\"tray_2\" class=\"tray_item icon_files\"><span class=\"tray_glyph luna_icon\">&#xf07b;</span></div>\n"
    "      </div>\n"
    "      <div id=\"mb_clip\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf0ea;</span></div>\n"
    "      <div id=\"mb_wifi\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf1eb;</span> Wi-Fi</div>\n"
    "      <div id=\"mb_bat\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf240;</span> 98%</div>\n"
    "      <div id=\"mb_cc\" class=\"mb_item mb_status\"><span class=\"luna_icon\">&#xf1de;</span></div>\n"
    "      <div id=\"mb_weather\" class=\"mb_item mb_status\" title=\"Weather\">\n"
    "        <span class=\"luna_icon\" id=\"mb_weather_icon\">&#xf2c9;</span>\n"
    "        <span id=\"mb_weather_temp\">—</span>\n"
    "      </div>\n"
    "      <div id=\"mb_clock\" class=\"mb_item\">Tue Jul 28  23:00</div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Window actions, opened by a title-bar or window-list right click. -->\n"
    "  <div id=\"win_menu\" class=\"menu_panel hidden\">\n"
    "    <span id=\"win_menu_title\" class=\"menu_section_label\">Window</span>\n"
    "    <div id=\"wm_activate\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf2d0;</span><span class=\"mi_label\">Activate</span></div>\n"
    "    <div id=\"wm_minimize\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf2d1;</span><span class=\"mi_label\">Minimize</span></div>\n"
    "    <div id=\"wm_maximize\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf2d0;</span><span class=\"mi_label\">Maximize</span></div>\n"
    "    <div id=\"wm_fullscreen\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf065;</span><span class=\"mi_label\">Fullscreen</span></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wm_tile_left\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf053;</span><span class=\"mi_label\">Tile Left</span></div>\n"
    "    <div id=\"wm_tile_right\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf054;</span><span class=\"mi_label\">Tile Right</span></div>\n"
    "    <div id=\"wm_center\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf192;</span><span class=\"mi_label\">Center</span></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wm_close\" class=\"menu_item mi_destructive\"><span class=\"mi_sym luna_icon\">&#xf00d;</span><span class=\"mi_label\">Close</span></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Alt+Tab switcher.  Keep one element per MAX_SWITCHER_SLOTS. -->\n"
    "  <div id=\"switcher\" class=\"switcher_overlay hidden\">\n"
    "    <div id=\"switcher_strip\">\n"
    "      <div id=\"sw_0\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_1\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_2\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_3\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_4\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_5\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_6\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_7\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_8\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_9\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_10\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "      <div id=\"sw_11\" class=\"switcher_item\"><span class=\"sw_app\">app</span><span class=\"sw_title\">Window</span></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Wi-Fi menu (backed by ConnMan, with NetworkManager fallback) -->\n"
    "  <div id=\"wifi_menu\" class=\"menu_panel hidden\">\n"
    "    <div id=\"wifi_head\">\n"
    "      <span id=\"wifi_title\">Wi-Fi</span>\n"
    "      <div class=\"cc_toggle\" id=\"wifi_power\"><div class=\"cc_knob\"></div></div>\n"
    "    </div>\n"
    "    <span id=\"wifi_status\">Checking network service...</span>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wifi_0\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_1\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_2\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_3\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_4\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_5\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_6\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_7\" class=\"menu_item wifi_network hidden\"><span class=\"mi_sym luna_icon\">&#xf1eb;</span><span class=\"mi_label\">Network</span><span class=\"wifi_signal\"></span></div>\n"
    "    <div id=\"wifi_credentials\" class=\"hidden\">\n"
    "      <span id=\"wifi_selected\">Connect to network</span>\n"
    "      <input type=\"password\" id=\"wifi_password\" placeholder=\"Password (leave blank if saved/open)\">\n"
    "      <div id=\"wifi_connect\" class=\"dlg_btn primary\">Connect</div>\n"
    "    </div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"wifi_scan\" class=\"menu_item\"><span class=\"mi_sym luna_icon\">&#xf021;</span><span class=\"mi_label\">Scan for Networks</span></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Luna Dropdown Menu -->\n"
    "  <div id=\"luna_menu\" class=\"menu_panel hidden\">\n"
    "    <span class=\"menu_section_label\">System</span>\n"
    "    <div class=\"menu_item\" id=\"mi_about\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf186;</span>\n"
    "      <span class=\"mi_label\">About This PC...</span>\n"
    "    </div>\n"
    "    <div class=\"menu_item\" id=\"mi_settings\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf013;</span>\n"
    "      <span class=\"mi_label\">System Settings...</span>\n"
    "      <span class=\"mi_key\">⌘,</span>\n"
    "    </div>\n"
    "    <div class=\"menu_item\" id=\"mi_launchpad\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf135;</span>\n"
    "      <span class=\"mi_label\">Launchpad</span>\n"
    "      <span class=\"mi_key\">F4</span>\n"
    "    </div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div class=\"menu_item\" id=\"mi_restart\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf021;</span>\n"
    "      <span class=\"mi_label\">Restart...</span>\n"
    "    </div>\n"
    "    <div class=\"menu_item mi_destructive\" id=\"mi_shutdown\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf011;</span>\n"
    "      <span class=\"mi_label\">Shut Down...</span>\n"
    "    </div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div class=\"menu_item mi_destructive\" id=\"mi_logout\">\n"
    "      <span class=\"mi_sym luna_icon\">&#xf08b;</span>\n"
    "      <span class=\"mi_label\">Log Out...</span>\n"
    "      <span class=\"mi_key\">⇧⌘Q</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Clipboard history.  The shell populates and wires these items in C. -->\n"
    "  <div id=\"clip_menu\" class=\"menu_panel hidden\">\n"
    "    <div class=\"menu_section_label\">Clipboard</div>\n"
    "    <div id=\"clip_empty\" class=\"clip_empty\">No recent copies</div>\n"
    "    <div id=\"clip_0\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">1</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_1\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">2</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_2\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">3</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_3\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">4</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_4\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">5</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_5\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">6</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_6\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">7</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div id=\"clip_7\" class=\"menu_item clip_item hidden\"><div class=\"mi_sym\">8</div><div class=\"mi_label clip_preview\">—</div></div>\n"
    "    <div class=\"menu_sep\"></div>\n"
    "    <div id=\"clip_clear\" class=\"menu_item mi_destructive\"><div class=\"mi_sym\">✕</div><div class=\"mi_label\">Clear History</div></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Control Center -->\n"
    "  <div id=\"control_center\" class=\"menu_panel hidden\">\n"
    "    <div class=\"cc_row\">\n"
    "      <div class=\"cc_cell\">\n"
    "        <div class=\"cc_toggle on\" id=\"cc_wifi\"><div class=\"cc_knob\"></div></div>\n"
    "        <span class=\"cc_label\">Wi-Fi</span>\n"
    "      </div>\n"
    "      <div class=\"cc_cell\">\n"
    "        <div class=\"cc_toggle on\" id=\"cc_bt\"><div class=\"cc_knob\"></div></div>\n"
    "        <span class=\"cc_label\">Bluetooth</span>\n"
    "      </div>\n"
    "      <div class=\"cc_cell\">\n"
    "        <div class=\"cc_toggle\" id=\"cc_night\"><div class=\"cc_knob\"></div></div>\n"
    "        <span class=\"cc_label\">Night Shift</span>\n"
    "      </div>\n"
    "    </div>\n"
    "    <span class=\"cc_section\">Display & Sound</span>\n"
    "    <div class=\"cc_track\" id=\"bright_track\">\n"
    "      <div class=\"cc_fill\" id=\"bright_fill\" style=\"width: 75%;\"></div>\n"
    "      <div class=\"cc_thumb\" id=\"bright_thumb\" style=\"left: 73%;\"></div>\n"
    "    </div>\n"
    "    <div class=\"cc_track\" id=\"vol_track\">\n"
    "      <div class=\"cc_fill\" id=\"vol_fill\" style=\"width: 60%;\"></div>\n"
    "      <div class=\"cc_thumb\" id=\"vol_thumb\" style=\"left: 58%;\"></div>\n"
    "    </div>\n"
    "    <span class=\"cc_section\">System Performance</span>\n"
    "    <div class=\"cc_stat_row\">\n"
    "      <span class=\"cc_stat_label\">CPU</span>\n"
    "      <div class=\"cc_bar\"><div class=\"cc_bar_fill\" id=\"cc_cpu_fill\" style=\"width: 24%;\"></div></div>\n"
    "    </div>\n"
    "    <div class=\"cc_stat_row\">\n"
    "      <span class=\"cc_stat_label\">RAM</span>\n"
    "      <div class=\"cc_bar\"><div class=\"cc_bar_fill\" id=\"cc_mem_fill\" style=\"width: 48%;\"></div></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Weather popover (Open-Meteo; mirrors qberry-weather.js) -->\n"
    "  <div id=\"weather_menu\" class=\"menu_panel hidden\">\n"
    "    <div id=\"weather_search\">\n"
    "      <input type=\"text\" id=\"weather_city_input\" placeholder=\"City (e.g. Tokyo)\">\n"
    "      <div id=\"weather_go\" class=\"dlg_btn primary\">Go</div>\n"
    "    </div>\n"
    "    <div id=\"weather_body\">\n"
    "      <span id=\"weather_hint\">Locating…</span>\n"
    "      <div id=\"weather_content\" class=\"hidden\">\n"
    "        <div id=\"weather_city_label\">—</div>\n"
    "        <div id=\"weather_main\">\n"
    "          <span class=\"luna_icon\" id=\"weather_icon\">&#xf185;</span>\n"
    "          <div>\n"
    "            <div id=\"weather_temp\">—°C</div>\n"
    "            <div id=\"weather_desc\">—</div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div id=\"weather_stats_row\">\n"
    "          <span id=\"weather_feels\">Feels —</span>\n"
    "          <span id=\"weather_hum\">—%</span>\n"
    "          <span id=\"weather_wind\">— km/h</span>\n"
    "        </div>\n"
    "        <div id=\"weather_forecast\">\n"
    "          <div id=\"wf_0\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_1\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_2\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_3\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "          <div id=\"wf_4\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <span id=\"weather_error\" class=\"hidden\">Weather unavailable</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Desktop Widgets -->\n"
    "  <div id=\"widget_clock\" class=\"widget\">\n"
    "    <div id=\"wg_time\">23:00</div>\n"
    "    <div id=\"wg_date\">Tuesday, July 28</div>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"widget_stats\" class=\"widget\">\n"
    "    <div class=\"st_row\">\n"
    "      <span class=\"st_label\">CPU Usage</span>\n"
    "      <span class=\"st_val\" id=\"st_cpu_val\">24%</span>\n"
    "    </div>\n"
    "    <div class=\"st_bar\"><div class=\"st_fill\" id=\"st_cpu_fill\" style=\"width: 24%;\"></div></div>\n"
    "\n"
    "    <div class=\"st_row\" style=\"margin-top: 12px;\">\n"
    "      <span class=\"st_label\">Memory</span>\n"
    "      <span class=\"st_val\" id=\"st_mem_val\">7.8 / 16 GB</span>\n"
    "    </div>\n"
    "    <div class=\"st_bar\"><div class=\"st_fill g_mem\" id=\"st_mem_fill\" style=\"width: 48%;\"></div></div>\n"
    "\n"
    "    <div class=\"st_row\" style=\"margin-top: 12px;\">\n"
    "      <span class=\"st_label\">Storage</span>\n"
    "      <span class=\"st_val\">142 / 512 GB</span>\n"
    "    </div>\n"
    "    <div class=\"st_bar\"><div class=\"st_fill g_disk\" style=\"width: 28%;\"></div></div>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"widget_weather\" class=\"widget\">\n"
    "    <div class=\"st_row\">\n"
    "      <span class=\"st_label\" id=\"wg_wx_city\">Weather</span>\n"
    "      <span class=\"st_val\" id=\"wg_wx_temp\">—</span>\n"
    "    </div>\n"
    "    <div id=\"wg_wx_main\">\n"
    "      <span class=\"luna_icon\" id=\"wg_wx_icon\">&#xf2c9;</span>\n"
    "      <span id=\"wg_wx_desc\">Fetching…</span>\n"
    "    </div>\n"
    "    <div id=\"wg_wx_forecast\">\n"
    "      <div id=\"wg_wf_0\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_1\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_2\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_3\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "      <div id=\"wg_wf_4\" class=\"wf_day\"><div class=\"wf_name\">—</div><div class=\"wf_icon luna_icon\">&#xf2c9;</div><div class=\"wf_temp\">—</div></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Dock -->\n"
    "  <div id=\"dock\">\n"
    "    <div class=\"dock_item\" id=\"dock_files\">\n"
    "      <div class=\"dock_icon g_files luna_icon\">&#xf07b;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_files\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_launchpad\">\n"
    "      <div class=\"dock_icon g_launchpad luna_icon\">&#xf135;</div>\n"
    "      <div class=\"dock_dot spacer\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_terminal\">\n"
    "      <div class=\"dock_icon g_terminal luna_icon\">&#xf120;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_terminal\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_browser\">\n"
    "      <div class=\"dock_icon g_browser luna_icon\">&#xf0ac;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_browser\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_editor\">\n"
    "      <div class=\"dock_icon g_editor luna_icon\">&#xf15c;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_editor\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_music\">\n"
    "      <div class=\"dock_icon g_music luna_icon\">&#xf001;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_music\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_item\" id=\"dock_settings\">\n"
    "      <div class=\"dock_icon g_settings luna_icon\">&#xf013;</div>\n"
    "      <div class=\"dock_dot\" id=\"dot_settings\"></div>\n"
    "    </div>\n"
    "    <div class=\"dock_sep\"></div>\n"
    "    <div class=\"dock_item\" id=\"dock_trash\">\n"
    "      <div class=\"dock_icon g_trash luna_icon\">&#xf1f8;</div>\n"
    "      <div class=\"dock_dot spacer\"></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Launchpad Overlay -->\n"
    "  <div id=\"launchpad\" class=\"hidden\">\n"
    "    <input type=\"text\" id=\"lp_search\" placeholder=\"Search applications\">\n"
    "    <div id=\"lp_grid\">\n"
    "      <div class=\"lp_app\" id=\"lp_files\">\n"
    "        <div class=\"lp_icon g_files luna_icon\">&#xf07b;</div>\n"
    "        <span class=\"lp_label\">Files</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_terminal\">\n"
    "        <div class=\"lp_icon g_terminal luna_icon\">&#xf120;</div>\n"
    "        <span class=\"lp_label\">Terminal</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_browser\">\n"
    "        <div class=\"lp_icon g_browser luna_icon\">&#xf0ac;</div>\n"
    "        <span class=\"lp_label\">Browser</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_editor\">\n"
    "        <div class=\"lp_icon g_editor luna_icon\">&#xf15c;</div>\n"
    "        <span class=\"lp_label\">Editor</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_music\">\n"
    "        <div class=\"lp_icon g_music luna_icon\">&#xf001;</div>\n"
    "        <span class=\"lp_label\">Music</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_settings\">\n"
    "        <div class=\"lp_icon g_settings luna_icon\">&#xf013;</div>\n"
    "        <span class=\"lp_label\">Settings</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_demo\">\n"
    "        <div class=\"lp_icon g_demo luna_icon\">&#xf121;</div>\n"
    "        <span class=\"lp_label\">GTK Demo</span>\n"
    "      </div>\n"
    "      <div class=\"lp_app\" id=\"lp_hello\">\n"
    "        <div class=\"lp_icon g_hello luna_icon\">&#xf118;</div>\n"
    "        <span class=\"lp_label\">Hello GTK</span>\n"
    "      </div>\n"
    "    </div>\n"
    "    <span id=\"lp_hint\">Press Esc to close Launchpad</span>\n"
    "  </div>\n"
    "\n"
    "  <!-- Confirmation Dialog Overlay -->\n"
    "  <div id=\"confirm_overlay\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"confirm_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"confirm_box\" class=\"alert_box dialog_window dialog_alert\" role=\"dialog\" aria-modal=\"false\" aria-labelledby=\"confirm_title\" aria-describedby=\"confirm_msg\">\n"
    "      <div class=\"tl tl_red\" id=\"ctl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"ctl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"ctl_max\"></div>\n"
    "      <div id=\"confirm_drag\"></div>\n"
    "      <div id=\"confirm_content\">\n"
    "        <div id=\"confirm_icon\" class=\"luna_icon\" aria-hidden=\"true\">&#xf011;</div>\n"
    "        <div id=\"confirm_copy\">\n"
    "          <div id=\"confirm_title\">Shut Down?</div>\n"
    "          <div id=\"confirm_msg\">Open applications will close. Save your work before continuing.</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"confirm_btns\">\n"
    "        <button id=\"confirm_cancel\" class=\"dlg_btn\">Cancel</button>\n"
    "        <button id=\"confirm_ok\" class=\"dlg_btn danger\">Shut Down</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Settings Sheet Window -->\n"
    "  <div id=\"settings_win\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"settings_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"settings_sheet\" class=\"sheet_box dialog_window\">\n"
    "      <div class=\"tl tl_red\" id=\"stl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"stl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"stl_max\"></div>\n"
    "      <div id=\"settings_drag\"></div>\n"
    "      <div id=\"settings_title\">System Settings</div>\n"
    "      <div id=\"settings_body\">\n"
    "        <div id=\"settings_sidebar\">\n"
    "          <div class=\"stab active\" id=\"stab_apps\"><span class=\"stab_icon luna_icon\">&#xf013;</span> Applications</div>\n"
    "          <div class=\"stab\" id=\"stab_disp\"><span class=\"stab_icon luna_icon\">&#xf108;</span> Appearance</div>\n"
    "          <div class=\"stab\" id=\"stab_keyboard\"><span class=\"stab_icon luna_icon\">&#xf11c;</span> Keyboard</div>\n"
    "          <div class=\"stab\" id=\"stab_wm\"><span class=\"stab_icon luna_icon\">&#xf2d0;</span> Windows</div>\n"
    "        </div>\n"
    "        <div id=\"settings_content\">\n"
    "          <!-- Apps Panel -->\n"
    "          <div id=\"settings_panel_apps\">\n"
    "            <span class=\"panel_heading\">Default Applications</span>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\">File Manager</span>\n"
    "              <input type=\"text\" id=\"pref_files\" class=\"pref_input\" value=\"luna-fm\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\">Terminal</span>\n"
    "              <input type=\"text\" id=\"pref_terminal\" class=\"pref_input\" value=\"foot\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\">Web Browser</span>\n"
    "              <input type=\"text\" id=\"pref_browser\" class=\"pref_input\" value=\"firefox\">\n"
    "            </div>\n"
    "            <div class=\"pref_row\">\n"
    "              <span class=\"pref_label\">Text Editor</span>\n"
    "              <input type=\"text\" id=\"pref_editor\" class=\"pref_input\" value=\"luna-edit\">\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "          <!-- Appearance Panel -->\n"
    "          <div id=\"settings_panel_disp\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Desktop Skin</span>\n"
    "            <span class=\"pref_hint\">Choose a complete desktop look. Colors apply immediately; taskbar and deskbar skins also move the shell chrome.</span>\n"
    "            <div id=\"skin_cards\" role=\"radiogroup\" aria-label=\"Desktop skin\">\n"
    "              <div class=\"skin_card selected\" id=\"skin_0\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_0\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_0_name\">Luna Moonlight</span><span class=\"skin_desc\" id=\"skin_0_desc\">The built-in Luna desktop</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_1\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_1\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_1_name\">External skin</span><span class=\"skin_desc\" id=\"skin_1_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_2\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_2\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_2_name\">External skin</span><span class=\"skin_desc\" id=\"skin_2_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_3\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_3\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_3_name\">External skin</span><span class=\"skin_desc\" id=\"skin_3_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_4\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_4\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_4_name\">External skin</span><span class=\"skin_desc\" id=\"skin_4_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_5\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_5\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_5_name\">External skin</span><span class=\"skin_desc\" id=\"skin_5_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_6\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_6\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_6_name\">External skin</span><span class=\"skin_desc\" id=\"skin_6_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_7\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_7\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_7_name\">External skin</span><span class=\"skin_desc\" id=\"skin_7_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_8\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_0\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_8_name\">External skin</span><span class=\"skin_desc\" id=\"skin_8_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_9\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_1\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_9_name\">External skin</span><span class=\"skin_desc\" id=\"skin_9_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_10\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_2\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_10_name\">External skin</span><span class=\"skin_desc\" id=\"skin_10_desc\">Discovered automatically</span></div></div>\n"
    "              <div class=\"skin_card hidden\" id=\"skin_11\" role=\"radio\" tabindex=\"0\"><div class=\"skin_preview skin_preview_0\"></div><div class=\"skin_copy\"><span class=\"skin_name\" id=\"skin_11_name\">External skin</span><span class=\"skin_desc\" id=\"skin_11_desc\">Discovered automatically</span></div></div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"panel_heading\">Desktop Wallpaper</span>\n"
    "            <div id=\"wp_thumbs_row\">\n"
    "              <div class=\"wp_thumb wp_t_night selected\" id=\"wp_night\"></div>\n"
    "              <div class=\"wp_thumb wp_t_ocean\" id=\"wp_ocean\"></div>\n"
    "              <div class=\"wp_thumb wp_t_forest\" id=\"wp_forest\"></div>\n"
    "              <div class=\"wp_thumb wp_t_sunset\" id=\"wp_sunset\"></div>\n"
    "            </div>\n"
    "            <div class=\"wp_label_row\">\n"
    "              <span class=\"wp_lbl\">Night Sky</span>\n"
    "              <span class=\"wp_lbl\">Deep Ocean</span>\n"
    "              <span class=\"wp_lbl\">Pine Forest</span>\n"
    "              <span class=\"wp_lbl\">Dusk Sunset</span>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"panel_heading\" style=\"margin-top: 16px;\">Cursor Theme</span>\n"
    "            <div id=\"cur_thumbs_row\">\n"
    "              <div class=\"cur_card selected\" id=\"cur_aero\">\n"
    "                <div class=\"cur_preview cur_p_aero\"></div>\n"
    "                <span class=\"cur_name\">Aero Light</span>\n"
    "                <span class=\"cur_desc\">Modern translucent</span>\n"
    "              </div>\n"
    "              <div class=\"cur_card\" id=\"cur_miku\">\n"
    "                <div class=\"cur_preview cur_p_miku\"></div>\n"
    "                <span class=\"cur_name\">Cyan Magic</span>\n"
    "                <span class=\"cur_desc\">Vibrant glow</span>\n"
    "              </div>\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "          <!-- Keyboard panel: selecting a card applies and saves immediately. -->\n"
    "          <div id=\"settings_panel_keyboard\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Keyboard Layout</span>\n"
    "            <span class=\"pref_hint\">Choose the physical key layout. The change applies immediately to every Wayland application.</span>\n"
    "            <span id=\"kb_current\" class=\"kb_current\">Current: System default</span>\n"
    "            <div id=\"kb_thumbs_row\" role=\"radiogroup\" aria-label=\"Keyboard layout\">\n"
    "              <div class=\"kb_card\" id=\"kb_jp\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">日本語 (JIS)</span><span class=\"kb_desc\">Japanese keyboard</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_jp_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">日本語 + US</span><span class=\"kb_desc\">Alt+Shift to switch</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">English (US)</span><span class=\"kb_desc\">US QWERTY</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_de_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">Deutsch + US</span><span class=\"kb_desc\">German / English</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_fr_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">Français + US</span><span class=\"kb_desc\">French / English</span></div>\n"
    "              <div class=\"kb_card\" id=\"kb_kr_us\" role=\"radio\" tabindex=\"0\"><span class=\"kb_name\">한국어 + US</span><span class=\"kb_desc\">Korean / English</span></div>\n"
    "            </div>\n"
    "            <span class=\"kb_help\">複数配列では Alt + Shift で切り替えられます。日本語キーボードを固定する場合は「日本語 (JIS)」を選択してください。</span>\n"
    "          </div>\n"
    "\n"
    "          <!-- Window-management panel: lightweight compositor settings. -->\n"
    "          <div id=\"settings_panel_wm\" class=\"hidden\">\n"
    "            <span class=\"panel_heading\">Window Management</span>\n"
    "            <span class=\"pref_hint\">Changes apply immediately and are saved with the other desktop settings.</span>\n"
    "\n"
    "            <div class=\"wm_pref\" id=\"wm_snap\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Edge snapping</span><span class=\"wm_pref_desc\">Tile windows at the left or right edge.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_top_maximize\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Maximize at top edge</span><span class=\"wm_pref_desc\">Use the classic behavior when dragging a window to the top edge.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_double_click\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Double-click title bar</span><span class=\"wm_pref_desc\">Maximize or restore the active window.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_classic_titlebar\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Classic title bars</span><span class=\"wm_pref_desc\">Use the original solid bar and traffic-light controls for server-decorated windows.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_shortcuts\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Super-key shortcuts</span><span class=\"wm_pref_desc\">Arrows tile and restore; Super+D shows the desktop.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"pref_section\">Tiled window gap</span>\n"
    "            <div class=\"wm_choice_row\">\n"
    "              <div class=\"wm_choice\" id=\"wm_gap_0\" role=\"radio\" tabindex=\"0\">None</div>\n"
    "              <div class=\"wm_choice\" id=\"wm_gap_8\" role=\"radio\" tabindex=\"0\">Compact</div>\n"
    "              <div class=\"wm_choice\" id=\"wm_gap_16\" role=\"radio\" tabindex=\"0\">Comfortable</div>\n"
    "            </div>\n"
    "\n"
    "            <span class=\"pref_section\">Desktop behavior</span>\n"
    "            <div class=\"wm_pref\" id=\"wm_dock_mag\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Dock magnification</span><span class=\"wm_pref_desc\">Scale nearby icons while pointing at the dock.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "            <div class=\"wm_pref\" id=\"wm_restore\" role=\"switch\" tabindex=\"0\">\n"
    "              <div class=\"wm_pref_text\"><span class=\"wm_pref_name\">Restore previous session</span><span class=\"wm_pref_desc\">Reopen applications and restore window state after login.</span></div>\n"
    "              <div class=\"wm_switch\"><div class=\"wm_switch_knob\"></div></div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"settings_btns\">\n"
    "        <button class=\"dlg_btn\" id=\"settings_cancel\">Cancel</button>\n"
    "        <button class=\"dlg_btn primary\" id=\"settings_ok\">Apply Changes</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- About Box Window -->\n"
    "  <div id=\"about_win\" class=\"modal_sheet modeless_dialog hidden\">\n"
    "    <div id=\"about_backdrop\" class=\"modal_backdrop\"></div>\n"
    "    <div id=\"about_box\" class=\"sheet_box about_box dialog_window\">\n"
    "      <div class=\"tl tl_red\" id=\"tl_close\"></div>\n"
    "      <div class=\"tl tl_yellow\" id=\"tl_min\"></div>\n"
    "      <div class=\"tl tl_green\" id=\"tl_max\"></div>\n"
    "      <div id=\"about_drag\"></div>\n"
    "      <div id=\"about_content\">\n"
    "        <div id=\"about_icon\"><div class=\"luna_icon\" aria-hidden=\"true\">&#xf186;</div></div>\n"
    "        <div id=\"about_title\">Luna OS</div>\n"
    "        <div id=\"about_ver\"><span class=\"about_ver_dot\"></span>Version 1.0 · Moonlight Edition</div>\n"
    "        <div id=\"about_sep\"></div>\n"
    "        <div id=\"about_grid\">\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf085;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Shell</span>\n"
    "              <span class=\"spec_value\" id=\"about_shell\">Luna Shell 1.0</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf03e;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Compositor</span>\n"
    "              <span class=\"spec_value\" id=\"about_comp\">Luna UI Layer</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_brand\">&#xf17c;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Kernel</span>\n"
    "              <span class=\"spec_value\" id=\"about_kernel\">6.12.0-luna</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div class=\"about_spec\">\n"
    "            <div class=\"spec_icon luna_icon\">&#xf1c0;</div>\n"
    "            <div class=\"spec_text\">\n"
    "              <span class=\"spec_label\">Memory</span>\n"
    "              <span class=\"spec_value\" id=\"about_mem\">16.0 GB DDR5</span>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Notification Toast -->\n"
    "  <div id=\"toast\" class=\"hidden\">\n"
    "    <div id=\"toast_icon\" class=\"luna_icon\">&#xf186;</div>\n"
    "    <div id=\"toast_body\">\n"
    "      <div id=\"toast_title\">System Notification</div>\n"
    "      <div id=\"toast_msg\">Luna UI Engine updated to v2.0</div>\n"
    "    </div>\n"
    "    <div id=\"toast_close\">✕</div>\n"
    "  </div>\n"
    "</body>\n"
    "</html>\n"
