    "/* Hallmark · macrostructure: Workbench · tone: technical-utilitarian · anchor hue: violet\n"
    " * theme: Cobalt adapted to Luna Moonlight · enrichment: none · nav/footer: shell-native\n"
    " * audience: general desktop users · use: fast window and desktop control\n"
    " * contrast: pass (40–41) · chrome: shell-native · responsive: desktop-session scope\n"
    " */\n"
    "/* Hallmark · pre-emit critique: P5 H5 E4 S5 R5 V5 */\n"
    "/* Luna Shell — macOS Sonoma-inspired desktop for the Luna UI engine\n"
    " * Copyright © 2026 Yuichiro Nakada / Project Luna (Vespera) — MPL 2.0\n"
    " * Redesign pass: \"Moonlight\" signature palette & Modern Frosted Glass Dialogs Pass */\n"
    "\n"
    "/* Local faces keep startup deterministic and avoid a network fetch in browser\n"
    "   previews. Luna UI also resolves these roles through its native font loader. */\n"
    "@font-face {\n"
    "  font-family: \"Manrope\";\n"
    "  src: url(\"../fonts/web/Manrope-Regular.ttf\") format(\"truetype\");\n"
    "  font-display: swap;\n"
    "}\n"
    "@font-face {\n"
    "  font-family: \"Inter\";\n"
    "  src: url(\"../fonts/web/Inter-Regular.ttf\") format(\"truetype\");\n"
    "  font-display: swap;\n"
    "}\n"
    "\n"
    "/* Keep symbolic UI glyphs deterministic in both Chrome and luna-ui.  Emoji\n"
    "   depend on the host's colour-font support and were the source of missing or\n"
    "   mismatched icons in the native shell. */\n"
    "@font-face {\n"
    "  font-family: \"Luna Symbols\";\n"
    "  src: url(\"../fonts/LunaSymbols-Solid.otf\") format(\"opentype\");\n"
    "  font-display: block;\n"
    "}\n"
    "@font-face {\n"
    "  font-family: \"Luna Brands\";\n"
    "  src: url(\"../fonts/LunaSymbols-Brands.otf\") format(\"opentype\");\n"
    "  font-display: block;\n"
    "}\n"
    ".luna_icon { font-family: \"Luna Symbols\"; font-style: normal; speak: never; }\n"
    ".luna_brand { font-family: \"Luna Brands\"; font-style: normal; speak: never; }\n"
    ".tray_glyph.luna_icon, .win_glyph.luna_icon {\n"
    "  font-family: \"Luna Symbols\"; font-style: normal; speak: never;\n"
    "}\n"
    "\n"
    ":root {\n"
    "  /* Signature accent: moonlight gradient (violet → gold) */\n"
    "  --luna-accent:      #8d7bff;\n"
    "  --luna-accent-rgb:  141, 123, 255;\n"
    "  --luna-accent-2:    #c9a6ff;\n"
    "  --luna-accent-dark: #6a52e0;\n"
    "  --luna-gold:        #f4cf8c;\n"
    "  --luna-gold-rgb:    244, 207, 140;\n"
    "  --luna-glass:       rgba(20, 21, 42, 0.62);\n"
    "  --luna-glass-card:  rgba(255, 255, 255, 0.06);\n"
    "  --luna-glass-edge:  rgba(255, 255, 255, 0.16);\n"
    "  --luna-glass-glow:  rgba(141, 123, 255, 0.18);\n"
    "  --luna-text:        #f8f7ff;\n"
    "  --luna-text-dim:    rgba(215, 212, 242, 0.75);\n"
    "  --luna-text-muted:  rgba(165, 170, 210, 0.60);\n"
    "  /* Keep the display stack on Inter as well: luna-ui bakes one CSS-selected\n"
    "     sans face for the fast text path, and the browser receives this exact\n"
    "     family before falling back to the platform UI fonts. */\n"
    "  --display-font:     \"Inter\", -apple-system, BlinkMacSystemFont, \"SF Pro Display\", sans-serif;\n"
    "  --body-font:        \"Inter\", -apple-system, BlinkMacSystemFont, \"SF Pro Text\", sans-serif;\n"
    "  --radius-xl:        24px;\n"
    "  --radius-lg:        18px;\n"
    "  --radius-md:        12px;\n"
    "  --radius-sm:        8px;\n"
    "  --shadow-dialog:    0 16px 40px rgba(0, 0, 0, 0.28), 0 4px 12px rgba(0, 0, 0, 0.14), inset 0 1px 0 rgba(255, 255, 255, 0.20);\n"
    "  --dialog-radius:    14px;\n"
    "  --dialog-titlebar:  52px;\n"
    "  --dialog-surface:   rgba(31, 32, 46, 0.94);\n"
    "  --dialog-footer:    rgba(13, 14, 22, 0.54);\n"
    "  --dialog-divider:   rgba(255, 255, 255, 0.11);\n"
    "  --about-surface:    #1c1d2a;\n"
    "  --about-card:       #252738;\n"
    "  --about-card-hover: #2d3045;\n"
    "  --about-icon:       #35305c;\n"
    "  --about-border:     rgba(208, 203, 255, 0.14);\n"
    "  --skin-card:        rgba(255, 255, 255, 0.045);\n"
    "  --skin-card-hover:  rgba(255, 255, 255, 0.085);\n"
    "  --skin-preview-a:   #171b52;\n"
    "  --skin-preview-b:   #8d7bff;\n"
    "  --skin-preview-c:   #245edb;\n"
    "  --skin-preview-d:   #3c9b26;\n"
    "  --skin-preview-e:   #171814;\n"
    "  --skin-preview-f:   #a58a5c;\n"
    "  --skin-error:       #ff756f;\n"
    "  --color-settings-selected: rgba(141, 123, 255, 0.14);\n"
    "  --ease-out:         cubic-bezier(0.16, 1, 0.3, 1);\n"
    "  --ease-in:          cubic-bezier(0.7, 0, 0.84, 0);\n"
    "  --ease-in-out:      cubic-bezier(0.65, 0, 0.35, 1);\n"
    "  --dur-fast:         150ms;\n"
    "  --dur-short:        220ms;\n"
    "}\n"
    "\n"
    "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "html, body {\n"
    "  width: 100%;\n"
    "  height: 100%;\n"
    "  min-height: 100%;\n"
    "  background: #04040d;\n"
    "  font-family: var(--body-font);\n"
    "  color: var(--luna-text);\n"
    "  -webkit-font-smoothing: antialiased;\n"
    "}\n"
    "body { position: relative; min-width: 1024px; min-height: 720px; overflow: hidden; }\n"
    ".hidden { display: none !important; }\n"
    "\n"
    "@media (prefers-reduced-motion: reduce) {\n"
    "  * { animation-duration: 0.001ms !important; animation-iteration-count: 1 !important; transition-duration: 0.001ms !important; }\n"
    "}\n"
    "\n"
    "/* ── Background layer container ── */\n"
    "#bg_layer { position: absolute; inset: 0; }\n"
    "\n"
    "/* ── Wallpaper: Luna night sky ── */\n"
    "#wallpaper {\n"
    "  position: absolute; left: 0; top: 0; width: 100%; height: 100%;\n"
    "  background: linear-gradient(162deg,\n"
    "    #04040f 0%, #0a0d30 14%, #171b52 30%,\n"
    "    #2a2270 46%, #4d2a86 60%, #7c3a96 74%,\n"
    "    #a94a8e 86%, #c65f78 96%, #d67862 100%);\n"
    "}\n"
    "#wallpaper.ocean  { background: linear-gradient(162deg, #00050f 0%, #001030 18%, #002d5e 38%, #00588e 56%, #0092c2 72%, #35c2e8 86%, #8fe6f4 100%); }\n"
    "#wallpaper.forest { background: linear-gradient(162deg, #030a05 0%, #081c0e 20%, #12331a 38%, #1e5228 56%, #327a3a 72%, #5aa04a 86%, #a2cf6e 100%); }\n"
    "#wallpaper.sunset { background: linear-gradient(162deg, #0c0410 0%, #260a12 18%, #521424 36%, #8a2038 54%, #c8402e 70%, #ec7a2e 86%, #f8c25a 100%); }\n"
    "\n"
    "/* Aurora glow */\n"
    "#wp_aurora1 {\n"
    "  position: absolute; left: 0; top: 0; width: 100%; height: 100%;\n"
    "  background: radial-gradient(ellipse 95% 58% at 70% 10%, rgba(147, 130, 255, 0.28), transparent 70%);\n"
    "  mix-blend-mode: screen;\n"
    "  animation: auroraDrift1 26s ease-in-out infinite alternate;\n"
    "}\n"
    "#wp_aurora2 {\n"
    "  position: absolute; left: 0; top: 0; width: 100%; height: 100%;\n"
    "  background: radial-gradient(ellipse 68% 68% at 10% 90%, rgba(244, 207, 140, 0.18), transparent 72%);\n"
    "  mix-blend-mode: screen;\n"
    "  animation: auroraDrift2 32s ease-in-out infinite alternate;\n"
    "}\n"
    "@keyframes auroraDrift1 {\n"
    "  0%   { transform: translate(0, 0) scale(1); opacity: 0.9; }\n"
    "  100% { transform: translate(-2.5%, 2%) scale(1.06); opacity: 1; }\n"
    "}\n"
    "@keyframes auroraDrift2 {\n"
    "  0%   { transform: translate(0, 0) scale(1); opacity: 0.85; }\n"
    "  100% { transform: translate(2%, -3%) scale(1.08); opacity: 1; }\n"
    "}\n"
    "\n"
    "/* Moon + halo */\n"
    "#wp_moon_halo {\n"
    "  position: absolute;\n"
    "  left: calc(80% - 233px); top: calc(9% - 67px);\n"
    "  width: 300px; height: 300px; border-radius: 150px;\n"
    "  background: radial-gradient(circle, rgba(230, 220, 255, 0.18), rgba(244, 207, 140, 0.07) 46%, transparent 70%);\n"
    "  pointer-events: none;\n"
    "}\n"
    "#wp_moon {\n"
    "  position: absolute;\n"
    "  left: calc(80% - 166px); top: 9%;\n"
    "  width: 166px; height: 166px; border-radius: 83px;\n"
    "  background: radial-gradient(circle at 34% 30%, #ffffff 0%, #f0ecff 32%, #d6cef4 60%, #a8a0d8 100%);\n"
    "  box-shadow: 0 0 50px 16px rgba(200, 190, 255, 0.25), 0 0 110px 40px rgba(244, 207, 140, 0.12);\n"
    "  pointer-events: none;\n"
    "}\n"
    "\n"
    "/* Stars */\n"
    ".star { position: absolute; border-radius: 50%; background: #ffffff; animation: twinkle 4.5s ease-in-out infinite; }\n"
    "#wp_star1 { left: 10%; top: 13%; width: 3px;  height: 3px;  opacity: 0.90; animation-delay: 0.0s; }\n"
    "#wp_star2 { left: 24%; top: 7%;  width: 2px;  height: 2px;  opacity: 0.58; animation-delay: 0.6s; }\n"
    "#wp_star3 { left: 38%; top: 16%; width: 2px;  height: 2px;  opacity: 0.72; animation-delay: 1.2s; }\n"
    "#wp_star4 { left: 53%; top: 8%;  width: 3px;  height: 3px;  opacity: 0.68; animation-delay: 1.8s; }\n"
    "#wp_star5 { left: 64%; top: 22%; width: 2px;  height: 2px;  opacity: 0.52; animation-delay: 2.4s; }\n"
    "#wp_star6 { left: 6%;  top: 32%; width: 2px;  height: 2px;  opacity: 0.64; animation-delay: 3.0s; }\n"
    "#wp_star7 { left: 31%; top: 28%; width: 3px;  height: 3px;  opacity: 0.46; animation-delay: 3.6s; }\n"
    "#wp_star8 { left: 78%; top: 32%; width: 2px;  height: 2px;  opacity: 0.78; animation-delay: 4.1s; }\n"
    "@keyframes twinkle {\n"
    "  0%, 100% { opacity: 0.35; transform: scale(1); }\n"
    "  50%      { opacity: 1;    transform: scale(1.4); }\n"
    "}\n"
    "#wallpaper.wallpaper_static #wp_aurora1,\n"
    "#wallpaper.wallpaper_static #wp_aurora2,\n"
    "#wallpaper.wallpaper_static .star { animation: none; }\n"
    "/* ── Menu bar ── */\n"
    "#menubar {\n"
    "  position: absolute; left: 0; top: 0; width: 100%; height: 32px;\n"
    "  background-color: rgba(10, 11, 26, 0.75);\n"
    "  backdrop-filter: blur(30px) saturate(1.8);\n"
    "  -webkit-backdrop-filter: blur(30px) saturate(1.8);\n"
    "  border-bottom: 1px solid var(--luna-glass-edge);\n"
    "  box-shadow: 0 1px 0 rgba(255, 255, 255, 0.05) inset, 0 4px 12px rgba(0, 0, 0, 0.14);\n"
    "  display: flex; flex-direction: row; align-items: center; justify-content: space-between;\n"
    "  padding: 0 12px;\n"
    "  z-index: 400;\n"
    "}\n"
    "/* Skins with chrome=taskbar / menubar_edge=bottom pin the bar via layer-shell\n"
    " * and also mark #menubar.edge_bottom so single-framebuffer backends match. */\n"
    "#menubar.edge_bottom {\n"
    "  top: auto; bottom: 0;\n"
    "  border-bottom: 0;\n"
    "  border-top: 1px solid var(--luna-glass-edge);\n"
    "  box-shadow: 0 -1px 0 rgba(255, 255, 255, 0.05) inset, 0 -4px 12px rgba(0, 0, 0, 0.14);\n"
    "}\n"
    "#mb_left  { display: flex; flex-direction: row; align-items: center; gap: 4px; height: 32px; flex: 0 0 auto; min-width: 80px; }\n"
    "#mb_center {\n"
    "  flex: 1 1 auto; min-width: 0; overflow: hidden;\n"
    "  display: flex; flex-direction: row; align-items: center; justify-content: center;\n"
    "  height: 32px; padding: 0 12px;\n"
    "}\n"
    "#mb_right { display: flex; flex-direction: row; align-items: center; justify-content: flex-end; gap: 4px; height: 32px; flex: 0 0 auto; }\n"
    "\n"
    ".mb_item {\n"
    "  color: rgba(245, 245, 255, 0.92); font-size: 13px; text-align: center;\n"
    "  height: 24px; padding: 3px 10px; border-radius: 6px; cursor: pointer;\n"
    "  background-color: transparent; white-space: nowrap; flex-shrink: 0;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), color var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".mb_item:hover { background-color: rgba(255, 255, 255, 0.14); color: #ffffff; }\n"
    "#mb_logo    { width: 36px; }\n"
    "#mb_logo_glyph { width: 16px; height: 16px; color: #f0ecff; font-size: 16px; line-height: 16px; text-align: center; }\n"
    "#mb_app, .mb_app_name {\n"
    "  font-weight: 600; font-size: 13px; letter-spacing: 0.01em;\n"
    "  max-width: 160px; overflow: hidden; text-overflow: ellipsis;\n"
    "  color: rgba(255, 255, 255, 0.98); cursor: default;\n"
    "}\n"
    "#mb_app:hover { background-color: transparent; }\n"
    ".mb_status  { font-size: 12px; color: rgba(215, 222, 255, 0.80); }\n"
    "#mb_bat     { min-width: 44px; }\n"
    "#mb_wifi    { min-width: 58px; }\n"
    "#mb_clip    { min-width: 28px; font-size: 13px; }\n"
    "#mb_cc      { width: 30px; font-size: 14px; }\n"
    "#mb_clock   { min-width: 136px; font-size: 12px; font-weight: 500; letter-spacing: 0.02em; font-variant-numeric: tabular-nums; }\n"
    "\n"
    "/* Window list (center of menubar).  min-width:0 + overflow:hidden lets the\n"
    " * list take leftover space after #mb_left / #mb_right so the clock stays on\n"
    " * screen; chips then shrink instead of pushing the bar. */\n"
    "#win_list {\n"
    "  display: flex; flex-direction: row; align-items: center; justify-content: flex-start;\n"
    "  flex: 1 1 auto; width: 100%; min-width: 0; max-width: 100%;\n"
    "  gap: 6px; height: 26px; overflow: hidden;\n"
    "}\n"
    ".win_item {\n"
    "  display: flex; flex-direction: row; align-items: center;\n"
    "  flex: 0 1 auto; min-width: 48px; max-width: 140px; overflow: hidden;\n"
    "  width: auto; height: 24px; padding: 0 10px;\n"
    "  border-radius: 7px; cursor: pointer;\n"
    "  background-color: rgba(255, 255, 255, 0.08);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.08);\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), opacity var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".win_item:hover { background-color: rgba(255, 255, 255, 0.16); border-color: rgba(255, 255, 255, 0.18); }\n"
    ".win_item.active {\n"
    "  background: linear-gradient(120deg, rgba(var(--luna-accent-rgb), 0.38), rgba(var(--luna-gold-rgb), 0.22));\n"
    "  border-color: rgba(var(--luna-accent-rgb), 0.60);\n"
    "  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.20), 0 2px 8px rgba(0,0,0,0.2);\n"
    "}\n"
    ".win_item.minimized { opacity: 0.50; }\n"
    ".win_item.hidden { display: none !important; }\n"
    ".win_glyph {\n"
    "  width: 14px; flex: 0 0 14px; margin-right: 4px;\n"
    "  font-size: 12px; line-height: 14px; text-align: center; color: inherit;\n"
    "}\n"
    ".win_label {\n"
    "  color: #ffffff; font-size: 12px; font-weight: 500;\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "  min-width: 0; max-width: 118px; flex: 1 1 auto;\n"
    "}\n"
    "\n"
    "/* System tray */\n"
    "#tray_area {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 3px;\n"
    "  height: 24px; margin-right: 6px; padding-right: 8px;\n"
    "  border-right: 1px solid rgba(255, 255, 255, 0.12);\n"
    "}\n"
    ".tray_item {\n"
    "  width: 24px; height: 22px; border-radius: 6px; cursor: pointer;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".tray_item:hover { background-color: rgba(255, 255, 255, 0.15); }\n"
    ".tray_item.active { background-color: rgba(var(--luna-accent-rgb), 0.30); }\n"
    ".tray_item.hidden { display: none !important; }\n"
    "#tray_area.hidden { display: none !important; }\n"
    ".tray_glyph { color: rgba(225, 230, 255, 0.90); font-size: 12px; text-align: center; }\n"
    "\n"
    "/* ── Menu panels (Dropdowns) ── */\n"
    ".menu_panel {\n"
    "  position: absolute; top: 36px;\n"
    "  background: linear-gradient(165deg, rgba(22, 23, 46, 0.86) 0%, rgba(14, 15, 32, 0.92) 100%);\n"
    "  backdrop-filter: blur(32px) saturate(1.7);\n"
    "  -webkit-backdrop-filter: blur(32px) saturate(1.7);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.15);\n"
    "  border-radius: var(--radius-lg);\n"
    "  box-shadow: var(--shadow-dialog);\n"
    "  padding: 8px;\n"
    "  z-index: 650;\n"
    "  animation: menuFade 0.18s cubic-bezier(0.16, 1, 0.3, 1);\n"
    "}\n"
    "@keyframes menuFade {\n"
    "  from { opacity: 0; transform: scale(0.98); }\n"
    "  to   { opacity: 1; transform: scale(1); }\n"
    "}\n"
    "\n"
    "#luna_menu { left: 8px; width: 256px; }\n"
    "#win_menu  { left: 200px; width: 210px; }\n"
    "#clip_menu { right: 160px; left: auto; width: 288px; max-height: 420px; }\n"
    ".clip_empty {\n"
    "  display: block; height: 38px; padding: 10px 14px;\n"
    "  color: var(--luna-text-muted); font-size: 12px; text-align: center;\n"
    "}\n"
    ".clip_preview { max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n"
    "#clip_menu { width: 280px; }\n"
    "\n"
    ".menu_section_label {\n"
    "  display: block; height: 24px;\n"
    "  text-align: left; color: var(--luna-text-dim);\n"
    "  font-size: 11px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase;\n"
    "  padding: 6px 12px 2px 12px;\n"
    "}\n"
    "\n"
    ".menu_item {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 4px;\n"
    "  width: 100%; height: 32px;\n"
    "  padding: 0 10px 0 6px; border-radius: var(--radius-sm); cursor: pointer;\n"
    "  background-color: transparent;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), color var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".menu_item:hover {\n"
    "  background: linear-gradient(120deg, rgba(var(--luna-accent-rgb), 0.90), rgba(165, 128, 235, 0.90));\n"
    "  box-shadow: 0 2px 8px rgba(var(--luna-accent-rgb), 0.30);\n"
    "}\n"
    ".menu_item:hover .mi_sym,\n"
    ".menu_item:hover .mi_label,\n"
    ".menu_item:hover .mi_key { color: #ffffff !important; }\n"
    "\n"
    ".mi_sym {\n"
    "  width: 28px; flex: 0 0 28px;\n"
    "  color: rgba(205, 212, 255, 0.78); font-size: 13px; text-align: center;\n"
    "}\n"
    ".mi_label { flex: 1 1 auto; color: var(--luna-text); font-size: 13px; font-weight: 500; }\n"
    ".mi_key { color: var(--luna-text-muted); font-size: 11px; margin-left: 8px; }\n"
    "\n"
    ".mi_destructive .mi_label { color: #ff6b63; }\n"
    ".mi_destructive:hover { background: linear-gradient(120deg, #ff453a, #e03228) !important; }\n"
    "\n"
    ".menu_sep {\n"
    "  display: block; width: 92%; height: 1px;\n"
    "  background-color: rgba(255, 255, 255, 0.08);\n"
    "  margin: 4px auto;\n"
    "}\n"
    "\n"
    "/* ── Control Center ── */\n"
    "#control_center { right: 8px; width: 324px; height: auto; padding: 16px; }\n"
    "#wifi_menu, #bt_menu { right: 150px; width: 310px; height: auto; padding: 10px; }\n"
    "#wifi_head, #bt_head { display: flex; flex-direction: row; align-items: center; min-height: 34px; padding: 0 8px; }\n"
    "#wifi_title, #bt_title { flex: 1 1 auto; color: var(--luna-text); font-size: 14px; font-weight: 700; }\n"
    "#wifi_power, #bt_power { flex: 0 0 46px; }\n"
    "#wifi_status, #eth_status, #bt_status { display: block; color: var(--luna-text-muted); font-size: 11px; padding: 2px 8px 7px; }\n"
    "#eth_section { display: block; padding: 6px 8px 2px; }\n"
    ".wifi_network .mi_label, .eth_link .mi_label, .bt_device .mi_label { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    ".wifi_network.connected, .eth_link.connected, .bt_device.connected { background: rgba(var(--luna-accent-rgb), 0.20); }\n"
    ".wifi_network.connected .mi_sym, .eth_link.connected .mi_sym, .bt_device.connected .mi_sym { color: var(--luna-accent-2); }\n"
    ".wifi_signal, .eth_state, .bt_state { color: var(--luna-text-muted); font-size: 10px; min-width: 32px; text-align: right; }\n"
    "#wifi_credentials { padding: 8px 6px 4px; }\n"
    "#wifi_selected { display: block; color: var(--luna-text-dim); font-size: 11px; margin: 0 2px 6px; }\n"
    "#wifi_password { width: 100%; height: 32px; padding: 0 9px; margin-bottom: 7px; border-radius: 7px; background: rgba(0,0,0,.28); border: 1px solid rgba(255,255,255,.14); color: var(--luna-text); font-size: 12px; }\n"
    "#wifi_connect { width: 100%; }\n"
    "#cc_bt_open { cursor: pointer; }\n"
    ".net_tip {\n"
    "  display: block; margin: 6px 2px 2px; padding: 8px 10px;\n"
    "  border-radius: var(--radius-sm);\n"
    "  background: rgba(var(--luna-accent-rgb), 0.12);\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.28);\n"
    "  color: var(--luna-text-dim); font-size: 11px; line-height: 1.45;\n"
    "  white-space: pre-wrap;\n"
    "}\n"
    "#net_tip_line { display: block; color: var(--luna-text); font-size: 11px; font-weight: 500; }\n"
    ".cc_row { display: flex; flex-direction: row; gap: 10px; margin-bottom: 12px; }\n"
    ".cc_cell {\n"
    "  flex: 1 1 0;\n"
    "  display: flex; flex-direction: column; align-items: center; gap: 8px;\n"
    "  background: var(--luna-glass-card);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.08);\n"
    "  border-radius: var(--radius-md); padding: 12px 6px;\n"
    "}\n"
    ".cc_toggle {\n"
    "  width: 46px; height: 26px; border-radius: 13px;\n"
    "  background-color: rgba(120, 125, 155, 0.35);\n"
    "  cursor: pointer; position: relative;\n"
    "  transition: background-color var(--dur-fast) var(--ease-in-out);\n"
    "}\n"
    ".cc_toggle.on { background: linear-gradient(120deg, var(--luna-accent), var(--luna-accent-dark)); box-shadow: 0 2px 10px rgba(var(--luna-accent-rgb), 0.40); }\n"
    ".cc_knob {\n"
    "  position: absolute; left: 3px; top: 3px; width: 20px; height: 20px; border-radius: 50%;\n"
    "  background-color: #ffffff; box-shadow: 0 1px 4px rgba(0, 0, 0, 0.40);\n"
    "  transition: transform 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n"
    "}\n"
    ".cc_toggle.on .cc_knob { transform: translateX(20px); }\n"
    ".cc_label { color: var(--luna-text-dim); font-size: 11px; font-weight: 500; text-align: center; }\n"
    ".cc_section { display: block; text-align: left; color: var(--luna-text-muted); font-size: 11px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; margin: 12px 4px 6px 4px; }\n"
    ".cc_track { position: relative; height: 22px; border-radius: 11px; background-color: rgba(255, 255, 255, 0.10); border: 1px solid rgba(255, 255, 255, 0.06); margin: 0 2px 8px 2px; cursor: pointer; }\n"
    ".cc_fill  { position: absolute; left: 0; top: 0; height: 100%; width: 0%; border-radius: 11px; background: linear-gradient(90deg, var(--luna-accent-2), var(--luna-accent)); pointer-events: none; }\n"
    ".cc_thumb { position: absolute; left: 0; top: 1px; width: 18px; height: 18px; border-radius: 50%; background-color: #ffffff; box-shadow: 0 2px 6px rgba(0, 0, 0, 0.45); cursor: pointer; z-index: 2; }\n"
    ".cc_stat_row { display: flex; flex-direction: row; align-items: center; gap: 8px; margin: 6px 2px; }\n"
    ".cc_stat_label { color: var(--luna-text-dim); font-size: 11px; width: 32px; flex: 0 0 32px; text-align: left; font-weight: 600; }\n"
    ".cc_bar { flex: 1 1 auto; height: 6px; border-radius: 3px; background-color: rgba(255, 255, 255, 0.10); position: relative; overflow: hidden; }\n"
    ".cc_bar_fill { position: absolute; left: 0; top: 0; height: 100%; width: 40%; border-radius: 3px; background: linear-gradient(90deg, var(--luna-accent-2), var(--luna-accent)); }\n"
    "\n"
    "/* ── Desktop widgets ── */\n"
    ".widget {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, rgba(18, 19, 42, 0.52) 0%, rgba(10, 11, 26, 0.65) 100%);\n"
    "  backdrop-filter: blur(24px) saturate(1.6);\n"
    "  -webkit-backdrop-filter: blur(24px) saturate(1.6);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.12);\n"
    "  border-radius: 22px;\n"
    "  box-shadow: 0 10px 28px rgba(0, 0, 0, 0.22), inset 0 1px 0 rgba(255, 255, 255, 0.08);\n"
    "  padding: 16px 18px;\n"
    "}\n"
    "#widget_clock {\n"
    "  right: 24px; top: 52px; width: 220px; height: 110px;\n"
    "  transition: height var(--dur-short) var(--ease-out), padding var(--dur-short) var(--ease-out);\n"
    "}\n"
    "#widget_clock.stopwatch_mode { height: 160px; padding: 14px 16px; }\n"
    "#wg_clock_view { position: relative; width: 100%; height: 100%; }\n"
    "#wg_time {\n"
    "  font-family: var(--display-font);\n"
    "  color: #ffffff;\n"
    "  font-size: 46px; font-weight: 800; letter-spacing: -0.02em;\n"
    "  line-height: 1; padding-right: 28px;\n"
    "}\n"
    "#wg_date { color: var(--luna-text-dim); font-size: 12px; font-weight: 500; margin-top: 6px; }\n"
    ".wg_clock_icon {\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  width: 24px; height: 24px; border-radius: 8px;\n"
    "  color: var(--luna-text-dim); font-size: 12px; cursor: pointer;\n"
    "  background: rgba(255, 255, 255, 0.06);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.08);\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), color var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".wg_clock_icon:hover { background: rgba(255, 255, 255, 0.14); color: #ffffff; }\n"
    ".wg_clock_icon:focus-visible { outline: 2px solid var(--luna-accent-2); outline-offset: 2px; }\n"
    "#wg_stopwatch_open { position: absolute; right: 0; top: 0; }\n"
    "#wg_stopwatch_view { width: 100%; height: 100%; }\n"
    "#wg_stopwatch_head {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 8px;\n"
    "  width: 100%; height: 24px;\n"
    "}\n"
    "#wg_stopwatch_title {\n"
    "  flex: 1 1 auto; color: var(--luna-text); font-size: 12px; font-weight: 700;\n"
    "}\n"
    "#wg_stopwatch_state { color: var(--luna-text-muted); font-size: 10px; }\n"
    "#wg_stopwatch_time {\n"
    "  width: 100%; margin-top: 8px;\n"
    "  font-family: var(--display-font); font-variant-numeric: tabular-nums;\n"
    "  color: #ffffff; font-size: 34px; font-weight: 800; letter-spacing: -0.02em;\n"
    "  line-height: 1; text-align: center;\n"
    "}\n"
    "#wg_stopwatch_actions {\n"
    "  display: flex; flex-direction: row; gap: 8px;\n"
    "  width: 100%; margin-top: 12px;\n"
    "}\n"
    "#wg_stopwatch_actions .dlg_btn { flex: 1 1 0; min-width: 0; height: 30px; font-size: 12px; }\n"
    "#widget_stats.clock_below_stopwatch { top: 226px; }\n"
    "#widget_weather.clock_below_stopwatch { top: 398px; }\n"
    "#widget_stats { right: 24px; top: 176px; width: 220px; height: 156px; }\n"
    ".st_row { display: flex; flex-direction: row; justify-content: space-between; margin-top: 8px; }\n"
    ".st_label { color: var(--luna-text-dim); font-size: 11px; font-weight: 500; }\n"
    ".st_val   { color: #ffffff; font-size: 11px; font-weight: 700; text-align: right; }\n"
    ".st_bar   { height: 4px; border-radius: 2px; background-color: rgba(255, 255, 255, 0.10); margin-top: 5px; position: relative; overflow: hidden; }\n"
    ".st_fill  { position: absolute; left: 0; top: 0; height: 100%; width: 20%; border-radius: 2px; background: linear-gradient(90deg, var(--luna-accent-2), var(--luna-accent)); }\n"
    ".st_fill.g_mem  { background: linear-gradient(90deg, #bf5af2, #9b3fe0); }\n"
    ".st_fill.g_disk { background: linear-gradient(90deg, #30d158, #25a244); }\n"
    "\n"
    "/* ── Weather widget + popover (Open-Meteo) ── */\n"
    "#mb_weather { gap: 4px; min-width: 52px; }\n"
    "#mb_weather_temp { font-weight: 600; font-variant-numeric: tabular-nums; }\n"
    "#weather_menu { right: 120px; width: 288px; height: auto; padding: 0; overflow: hidden; z-index: 660; }\n"
    "#weather_search {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 6px;\n"
    "  padding: 10px 12px 8px; border-bottom: 1px solid rgba(255, 255, 255, 0.07);\n"
    "}\n"
    "#weather_city_input {\n"
    "  flex: 1 1 auto; height: 30px; padding: 0 10px; border-radius: 8px;\n"
    "  border: 1px solid rgba(255, 255, 255, 0.12); background: rgba(0, 0, 0, 0.35);\n"
    "  color: #fff; font-size: 12px;\n"
    "}\n"
    "#weather_go { flex: 0 0 auto; height: 30px; padding: 0 12px; font-size: 12px; }\n"
    "#weather_body { padding: 14px 16px 12px; }\n"
    "#weather_hint, #weather_error {\n"
    "  display: block; text-align: center; font-size: 12px; color: var(--luna-text-muted);\n"
    "  padding: 18px 8px;\n"
    "}\n"
    "#weather_error { color: #ff6b63; }\n"
    "#weather_city_label {\n"
    "  text-align: center; font-size: 11px; color: var(--luna-text-dim);\n"
    "  letter-spacing: 0.04em; margin-bottom: 10px;\n"
    "}\n"
    "#weather_main { display: flex; flex-direction: row; align-items: center; gap: 14px; margin-bottom: 12px; }\n"
    "#weather_icon { font-size: 36px; color: var(--luna-accent); width: 44px; text-align: center; }\n"
    "#weather_temp {\n"
    "  font-family: var(--display-font); font-size: 36px; font-weight: 700;\n"
    "  color: var(--luna-accent); line-height: 1;\n"
    "}\n"
    "#weather_desc { font-size: 11px; color: var(--luna-text-dim); margin-top: 4px; text-transform: capitalize; }\n"
    "#weather_stats_row {\n"
    "  display: flex; flex-direction: row; justify-content: space-between; gap: 8px;\n"
    "  font-size: 11px; color: var(--luna-text-muted);\n"
    "  border-top: 1px solid rgba(255, 255, 255, 0.06); padding-top: 10px; margin-bottom: 10px;\n"
    "}\n"
    "#weather_forecast, #wg_wx_forecast {\n"
    "  display: flex; flex-direction: row; gap: 6px; justify-content: space-between;\n"
    "}\n"
    ".wf_day { flex: 1 1 0; text-align: center; font-size: 11px; color: rgba(255, 255, 255, 0.55); }\n"
    ".wf_name { font-size: 10px; opacity: 0.7; margin-bottom: 2px; }\n"
    ".wf_icon { font-size: 16px; color: var(--luna-accent-2); margin: 4px 0; }\n"
    ".wf_temp { font-weight: 600; font-size: 12px; color: #fff; margin-top: 2px; }\n"
    ".wf_temp span { opacity: 0.55; font-size: 11px; font-weight: 500; }\n"
    "\n"
    "#widget_weather { right: 24px; top: 348px; width: 220px; height: 168px; }\n"
    "#wg_wx_main {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 8px;\n"
    "  margin-top: 8px; margin-bottom: 10px;\n"
    "}\n"
    "#wg_wx_icon { font-size: 22px; color: var(--luna-accent); width: 28px; text-align: center; }\n"
    "#wg_wx_desc { color: var(--luna-text-dim); font-size: 12px; font-weight: 500; }\n"
    "#widget_weather .wf_temp { font-size: 11px; }\n"
    "\n"
    "/* ── Calendar popover ── */\n"
    "#calendar_menu {\n"
    "  right: 8px; width: 300px; height: auto; padding: 12px 14px 14px;\n"
    "  z-index: 660;\n"
    "}\n"
    "#cal_head {\n"
    "  display: flex; flex-direction: row; align-items: center; justify-content: space-between;\n"
    "  margin-bottom: 10px; min-height: 28px;\n"
    "}\n"
    "#cal_month_label {\n"
    "  color: var(--luna-text); font-size: 14px; font-weight: 700;\n"
    "  letter-spacing: 0.01em; text-align: center; flex: 1 1 auto;\n"
    "}\n"
    ".cal_nav {\n"
    "  width: 28px; height: 28px; border-radius: 8px; cursor: pointer;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  color: var(--luna-text-dim); font-size: 12px;\n"
    "  background: rgba(255, 255, 255, 0.06);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.08);\n"
    "}\n"
    ".cal_nav:hover { background: rgba(255, 255, 255, 0.14); color: #ffffff; }\n"
    "#cal_weekdays {\n"
    "  display: flex; flex-direction: row; margin-bottom: 4px;\n"
    "}\n"
    ".cal_wd {\n"
    "  width: 36px; height: 22px; flex: 0 0 36px;\n"
    "  color: var(--luna-text-muted); font-size: 10px; font-weight: 700;\n"
    "  letter-spacing: 0.04em; text-align: center; line-height: 22px;\n"
    "}\n"
    "#cal_grid {\n"
    "  display: flex; flex-direction: row; flex-wrap: wrap;\n"
    "  width: 252px; margin: 0 auto 10px;\n"
    "}\n"
    ".cal_day {\n"
    "  position: relative;\n"
    "  width: 36px; height: 32px; flex: 0 0 36px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  border-radius: 9px; cursor: pointer;\n"
    "  color: var(--luna-text); font-size: 12px; font-weight: 500;\n"
    "}\n"
    ".cal_day.other { color: var(--luna-text-muted); opacity: 0.55; cursor: default; }\n"
    ".cal_day.today {\n"
    "  background: linear-gradient(120deg, rgba(var(--luna-accent-rgb), 0.42), rgba(var(--luna-gold-rgb), 0.22));\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.55);\n"
    "  color: #ffffff; font-weight: 700;\n"
    "}\n"
    ".cal_day.selected {\n"
    "  box-shadow: inset 0 0 0 1px rgba(var(--luna-gold-rgb), 0.55);\n"
    "}\n"
    ".cal_day.has_alarm::after {\n"
    "  content: \"\";\n"
    "  position: absolute;\n"
    "  left: 50%;\n"
    "  bottom: 3px;\n"
    "  width: 4px; height: 4px;\n"
    "  margin-left: -2px;\n"
    "  border-radius: 50%;\n"
    "  background: var(--luna-gold);\n"
    "  box-shadow: 0 0 6px rgba(var(--luna-gold-rgb), 0.7);\n"
    "}\n"
    ".cal_day.today.has_alarm::after { background: #ffffff; }\n"
    "#cal_today_btn { width: 100%; height: 30px; }\n"
    "\n"
    "#cal_alarm {\n"
    "  margin-top: 10px;\n"
    "  padding-top: 10px;\n"
    "  border-top: 1px solid rgba(255, 255, 255, 0.08);\n"
    "}\n"
    "#cal_alarm_head {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 8px;\n"
    "  margin-bottom: 8px; min-height: 20px;\n"
    "}\n"
    "#cal_alarm_bell { color: var(--luna-gold); font-size: 12px; width: 16px; text-align: center; }\n"
    "#cal_alarm_date {\n"
    "  flex: 1 1 auto; color: var(--luna-text); font-size: 12px; font-weight: 650;\n"
    "}\n"
    "#cal_alarm_count { color: var(--luna-text-muted); font-size: 10px; letter-spacing: 0.04em; }\n"
    "#cal_alarm_list { display: flex; flex-direction: column; gap: 4px; }\n"
    ".cal_al_row {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 8px;\n"
    "  min-height: 30px; padding: 0 8px;\n"
    "  border-radius: 8px;\n"
    "  background: rgba(255, 255, 255, 0.05);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.06);\n"
    "}\n"
    ".cal_al_time {\n"
    "  font-variant-numeric: tabular-nums;\n"
    "  color: var(--luna-gold); font-size: 12px; font-weight: 700;\n"
    "  width: 42px; flex: 0 0 42px;\n"
    "}\n"
    ".cal_al_label {\n"
    "  flex: 1 1 auto; min-width: 0;\n"
    "  color: var(--luna-text); font-size: 12px;\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "}\n"
    ".cal_al_repeat { color: var(--luna-text-muted); font-size: 10px; letter-spacing: 0.03em; }\n"
    ".cal_al_del {\n"
    "  width: 22px; height: 22px; flex: 0 0 22px; border-radius: 50%;\n"
    "  color: var(--luna-text-muted); font-size: 11px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  cursor: pointer;\n"
    "}\n"
    ".cal_al_del:hover { background: rgba(255, 107, 99, 0.18); color: #ff8b84; }\n"
    "#cal_alarm_empty {\n"
    "  color: var(--luna-text-muted); font-size: 11px; text-align: center;\n"
    "  padding: 6px 0 8px;\n"
    "}\n"
    "#cal_alarm_composer {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 6px;\n"
    "  margin-top: 6px;\n"
    "}\n"
    "#cal_alarm_time, #cal_alarm_note {\n"
    "  height: 30px; padding: 0 8px; border-radius: 8px;\n"
    "  border: 1px solid rgba(255, 255, 255, 0.12); background: rgba(0, 0, 0, 0.35);\n"
    "  color: #fff; font-size: 12px;\n"
    "}\n"
    "#cal_alarm_time { width: 58px; flex: 0 0 58px; font-variant-numeric: tabular-nums; }\n"
    "#cal_alarm_note { flex: 1 1 auto; min-width: 0; }\n"
    ".cal_chip {\n"
    "  height: 30px; padding: 0 8px; border-radius: 8px;\n"
    "  background: rgba(var(--luna-gold-rgb), 0.12);\n"
    "  border: 1px solid rgba(var(--luna-gold-rgb), 0.28);\n"
    "  color: var(--luna-gold); font-size: 11px; font-weight: 650;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  cursor: pointer; flex: 0 0 auto;\n"
    "}\n"
    ".cal_chip:hover { background: rgba(var(--luna-gold-rgb), 0.22); }\n"
    "#cal_alarm_add { flex: 0 0 auto; height: 30px; padding: 0 10px; font-size: 12px; }\n"
    "\n"
    "#mb_clock.ringing { color: var(--luna-gold); }\n"
    "\n"
    "#alarm_ring { z-index: 900; }\n"
    "#alarm_ring_card {\n"
    "  position: relative; z-index: 910;\n"
    "  width: 320px; padding: 28px 24px 22px;\n"
    "  border-radius: var(--dialog-radius);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.16);\n"
    "  background: linear-gradient(180deg, rgba(58, 48, 28, 0.92), rgba(22, 20, 32, 0.96) 42%);\n"
    "  box-shadow: 0 18px 48px rgba(0, 0, 0, 0.38), inset 0 1px rgba(255, 255, 255, 0.14);\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  animation: alarmCardIn 0.28s var(--ease-out);\n"
    "}\n"
    "@keyframes alarmCardIn {\n"
    "  from { opacity: 0; transform: scale(0.94) translateY(12px); }\n"
    "  to   { opacity: 1; transform: scale(1) translateY(0); }\n"
    "}\n"
    "#alarm_ring_orb {\n"
    "  width: 56px; height: 56px; border-radius: 50%;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 24px; color: #1a1408;\n"
    "  background: radial-gradient(circle at 30% 30%, #ffe7b0, var(--luna-gold) 58%, #c4923a);\n"
    "  box-shadow: 0 0 0 8px rgba(var(--luna-gold-rgb), 0.16), 0 10px 24px rgba(0, 0, 0, 0.28);\n"
    "  animation: alarmOrb 1.4s var(--ease-in-out) infinite alternate;\n"
    "}\n"
    "@keyframes alarmOrb {\n"
    "  from { transform: scale(1); }\n"
    "  to   { transform: scale(1.06); }\n"
    "}\n"
    "#alarm_ring_time {\n"
    "  font-family: var(--display-font); font-style: normal;\n"
    "  font-size: 44px; font-weight: 700; letter-spacing: -0.03em;\n"
    "  color: var(--luna-gold); margin-top: 16px; line-height: 1;\n"
    "  font-variant-numeric: tabular-nums;\n"
    "}\n"
    "#alarm_ring_label {\n"
    "  color: var(--luna-text); font-size: 15px; font-weight: 650;\n"
    "  margin-top: 8px; text-align: center;\n"
    "}\n"
    "#alarm_ring_when {\n"
    "  color: var(--luna-text-muted); font-size: 12px; margin-top: 4px;\n"
    "}\n"
    "#alarm_ring_actions {\n"
    "  display: flex; flex-direction: row; gap: 8px; width: 100%;\n"
    "  margin-top: 20px;\n"
    "}\n"
    "#alarm_snooze, #alarm_dismiss { flex: 1 1 50%; height: 34px; }\n"
    "@media (prefers-reduced-motion: reduce) {\n"
    "  #alarm_ring_card, #alarm_ring_orb { animation: none; }\n"
    "}\n"
    "\n"
    "/* Network detail dialog reuses About chrome sizing */\n"
    "#net_detail_box.about_box {\n"
    "  left: calc(50% - 210px); top: calc(42% - 250px);\n"
    "  width: 392px; height: auto; min-height: 520px;\n"
    "}\n"
    "#net_detail_content {\n"
    "  width: 100%; flex: 1 1 auto;\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  padding: 70px 22px 12px;\n"
    "}\n"
    "#net_detail_icon {\n"
    "  position: relative;\n"
    "  width: 56px; height: 56px; flex: 0 0 56px;\n"
    "  margin-bottom: 12px;\n"
    "  border-radius: var(--radius-md);\n"
    "  background: var(--about-icon);\n"
    "  box-shadow: 0 8px 22px rgba(0, 0, 0, 0.28), inset 0 1px rgba(255, 255, 255, 0.10);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "}\n"
    "#net_detail_icon .luna_icon { color: #e4e0f5; font-size: 28px; line-height: 1; }\n"
    "#net_detail_title {\n"
    "  font-family: var(--display-font);\n"
    "  color: var(--luna-text);\n"
    "  font-size: 18px; font-weight: 700; letter-spacing: -0.02em;\n"
    "  text-align: center; max-width: 320px;\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "}\n"
    "#net_detail_ver {\n"
    "  display: flex; align-items: center; gap: 6px;\n"
    "  color: rgba(232, 227, 255, 0.90);\n"
    "  font-size: 10px; font-weight: 600; letter-spacing: 0.035em;\n"
    "  margin-top: 6px; padding: 4px 9px 4px 8px;\n"
    "  background: rgba(var(--luna-accent-rgb), 0.10);\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.20);\n"
    "  border-radius: 999px;\n"
    "}\n"
    "#net_detail_sep { width: 100%; height: 1px; background: var(--dialog-divider); margin: 16px 0 12px; }\n"
    "#net_detail_grid { width: 100%; display: grid; grid-template-columns: 1fr; gap: 6px; }\n"
    "#net_detail_btns {\n"
    "  display: flex; flex-direction: row; align-items: center; justify-content: flex-end;\n"
    "  gap: 12px; width: 100%;\n"
    "  min-height: 56px; height: 56px; flex-basis: 56px;\n"
    "  padding: 12px 18px;\n"
    "  background: var(--dialog-footer);\n"
    "  border-top: 1px solid var(--dialog-divider);\n"
    "}\n"
    "#net_detail_btns .dlg_btn { min-width: 88px; }\n"
    "\n"
    "/* ── Traffic light window controls ── */\n"
    ".tl {\n"
    "  position: absolute; top: 16px; width: 12px; height: 12px; border-radius: 50%;\n"
    "  cursor: pointer; z-index: 20;\n"
    "  transition: transform 120ms var(--ease-out), opacity 120ms var(--ease-out);\n"
    "}\n"
    ".tl_red    { left: 16px; background-color: #ff5f57; box-shadow: 0 0 0 1px rgba(255, 60, 50, 0.3); }\n"
    ".tl_yellow { left: 34px; background-color: #febc2e; box-shadow: 0 0 0 1px rgba(255, 180, 0, 0.3); }\n"
    ".tl_green  { left: 52px; background-color: #28c840; box-shadow: 0 0 0 1px rgba(0, 180, 40, 0.3); }\n"
    ".tl:hover  { transform: scale(1.15); }\n"
    "\n"
    "/* ── Modal / sheet overlays ── */\n"
    ".modal_sheet {\n"
    "  position: absolute; left: 0; top: 0; width: 100%; height: 100%;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  z-index: 800; border-radius: 0;\n"
    "  animation: backdropFade var(--dur-short) var(--ease-out);\n"
    "}\n"
    "@keyframes backdropFade {\n"
    "  from { opacity: 0; }\n"
    "  to   { opacity: 1; }\n"
    "}\n"
    "\n"
    ".modal_backdrop {\n"
    "  position: absolute; inset: 0;\n"
    "  background: rgba(4, 5, 12, 0.56);\n"
    "  backdrop-filter: blur(18px) saturate(0.9) brightness(0.72);\n"
    "  -webkit-backdrop-filter: blur(18px) saturate(0.9) brightness(0.72);\n"
    "}\n"
    "\n"
    "/* Utility windows launched from the Luna menu are modeless.  On the Wayland\n"
    " * backend their surface input region is also clipped to .dialog_window, so\n"
    " * transparent pixels genuinely pass through to applications underneath. */\n"
    ".modeless_dialog { pointer-events: none; animation: none; }\n"
    ".modeless_dialog .modal_backdrop { display: none; }\n"
    ".modeless_dialog .dialog_window { pointer-events: auto; }\n"
    "\n"
    "/* ── Dialog window chrome ────────────────────────────────────────────────\n"
    " * Shared surface for every utility window and alert (Settings / About /\n"
    " * Confirm).  One definition drives background, border, radius, shadow,\n"
    " * entrance animation and the traffic-light offset; each dialog only adds\n"
    " * its own size, internal layout and (where relevant) content overrides. */\n"
    ".dialog_window {\n"
    "  position: absolute;\n"
    "  z-index: 810;\n"
    "  border: 1px solid var(--dialog-divider);\n"
    "  border-radius: var(--dialog-radius);\n"
    "  background: linear-gradient(180deg, rgba(53, 54, 70, 0.96), var(--dialog-surface) 14%, rgba(26, 27, 39, 0.97));\n"
    "  box-shadow: 0 16px 40px rgba(0, 0, 0, 0.28), 0 4px 12px rgba(0, 0, 0, 0.14), inset 0 1px rgba(255, 255, 255, 0.15);\n"
    "  overflow: hidden;\n"
    "  animation: dialogScale 0.24s cubic-bezier(0.16, 1, 0.3, 1);\n"
    "}\n"
    "@keyframes dialogScale {\n"
    "  from { opacity: 0; transform: scale(0.92) translateY(10px); }\n"
    "  to   { opacity: 1; transform: scale(1) translateY(0); }\n"
    "}\n"
    ".dialog_window .tl { top: 20px; }\n"
    "\n"
    "/* Alerts expose only the close control; minimize/maximize do not apply. */\n"
    ".dialog_alert .tl_yellow, .dialog_alert .tl_green { display: none; }\n"
    ".dialog_alert .tl_red { display: block; cursor: pointer; z-index: 12; }\n"
    "\n"
    "/* Shared title-bar drag handle for all three dialog types. */\n"
    "#about_drag, #settings_drag, #confirm_drag {\n"
    "  position: absolute; left: 0; top: 0; width: 100%;\n"
    "  height: var(--dialog-titlebar);\n"
    "  z-index: 10;\n"
    "  cursor: move;\n"
    "  background: transparent;\n"
    "  border-top-left-radius: inherit;\n"
    "  border-top-right-radius: inherit;\n"
    "}\n"
    "\n"
    "/* Shared footer bar (Settings & About action rows). */\n"
    "#settings_btns, #about_btns {\n"
    "  display: flex; flex-direction: row; align-items: center; justify-content: flex-end;\n"
    "  background: var(--dialog-footer);\n"
    "  border-top: 1px solid var(--dialog-divider);\n"
    "}\n"
    "#settings_btns {\n"
    "  gap: 12px;\n"
    "  min-height: 64px; height: 64px; flex-basis: 64px;\n"
    "  padding: 16px 20px;\n"
    "}\n"
    "#about_btns {\n"
    "  width: 100%;\n"
    "  min-height: 56px; height: 56px; flex-basis: 56px;\n"
    "  padding: 12px 18px;\n"
    "}\n"
    "#about_btns .dlg_btn { min-width: 88px; }\n"
    "\n"
    "/* ── Confirm / Alert dialog ── */\n"
    "#confirm_box.dialog_alert {\n"
    "  left: calc(50% - 210px); top: calc(44% - 120px);\n"
    "  width: 420px; height: 240px; min-height: 240px;\n"
    "  padding: 0;\n"
    "  display: flex; flex-direction: column;\n"
    "  text-align: left;\n"
    "}\n"
    "\n"
    "#confirm_content {\n"
    "  display: flex; flex-direction: row; align-items: flex-start;\n"
    "  gap: 16px;\n"
    "  width: 100%;\n"
    "  padding: 68px 28px 20px;\n"
    "}\n"
    "\n"
    "#confirm_icon {\n"
    "  width: 44px; height: 44px; flex: 0 0 44px;\n"
    "  border-radius: 12px;\n"
    "  background-color: rgba(236, 75, 68, 0.14);\n"
    "  background-image: none;\n"
    "  border: 1px solid rgba(255, 116, 109, 0.24);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  color: #ff756f; font-size: 20px;\n"
    "}\n"
    "#confirm_icon.restart {\n"
    "  background-color: rgba(244, 207, 140, 0.12);\n"
    "  border-color: rgba(244, 207, 140, 0.24);\n"
    "  color: var(--luna-gold);\n"
    "}\n"
    "#confirm_icon.logout {\n"
    "  background-color: rgba(var(--luna-accent-rgb), 0.13);\n"
    "  border-color: rgba(var(--luna-accent-rgb), 0.26);\n"
    "  color: var(--luna-accent-2);\n"
    "}\n"
    "\n"
    "#confirm_copy {\n"
    "  display: flex; flex-direction: column; align-items: flex-start;\n"
    "  gap: 7px; width: 304px; flex: 0 1 304px; min-width: 0;\n"
    "}\n"
    "\n"
    "#confirm_title {\n"
    "  color: #ffffff; font-family: var(--display-font);\n"
    "  font-size: 17px; line-height: 1.2; font-weight: 700;\n"
    "  letter-spacing: -0.02em; flex: 0 0 auto;\n"
    "}\n"
    "\n"
    "#confirm_msg {\n"
    "  color: var(--luna-text-dim); text-align: left;\n"
    "  font-size: 13px; line-height: 1.5;\n"
    "  width: 100%; min-height: 40px; padding: 0;\n"
    "}\n"
    "\n"
    "#confirm_btns {\n"
    "  position: absolute; left: 0; bottom: 0;\n"
    "  display: flex; flex-direction: row; justify-content: flex-end; align-items: center;\n"
    "  gap: 12px; width: 100%; height: 72px;\n"
    "  padding: 14px 20px;\n"
    "  background: var(--dialog-footer);\n"
    "  border-top: 1px solid var(--dialog-divider);\n"
    "}\n"
    "/* ── About This PC — a compact utility panel, not a second splash screen.\n"
    " * The icon, cards and type deliberately sit below the title-bar controls. */\n"
    "#about_box.about_box {\n"
    "  left: calc(50% - 210px); top: calc(42% - 230px);\n"
    "  width: 392px; height: auto; min-height: 500px;\n"
    "  display: flex; flex-direction: column; padding: 0;\n"
    "  background: var(--about-surface);\n"
    "  border-color: var(--about-border);\n"
    "}\n"
    "#about_content {\n"
    "  width: 100%; flex: 1 1 auto;\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  /* Keep this literal: the native CSS layout path does not resolve calc()\n"
    "   * inside padding.  70px leaves the dialog title bar completely clear. */\n"
    "  padding: 70px 22px 18px;\n"
    "}\n"
    "\n"
    "/* Moon badge — squircle + crescent-moon language, shared visually with\n"
    " * #confirm_icon above. */\n"
    "#about_icon {\n"
    "  position: relative;\n"
    "  width: 56px; height: 56px; flex: 0 0 56px;\n"
    "  margin-bottom: 12px;\n"
    "  border-radius: var(--radius-md);\n"
    "  background: var(--about-icon);\n"
    "  box-shadow: 0 8px 22px rgba(0, 0, 0, 0.28), inset 0 1px rgba(255, 255, 255, 0.10);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "}\n"
    "#about_icon .luna_icon { color: #e4e0f5; font-size: 30px; line-height: 1; }\n"
    "\n"
    "#about_title {\n"
    "  font-family: var(--display-font);\n"
    "  color: var(--luna-text);\n"
    "  font-size: 20px; font-weight: 700; letter-spacing: -0.02em;\n"
    "}\n"
    "#about_ver {\n"
    "  display: flex; align-items: center; gap: 6px;\n"
    "  color: rgba(232, 227, 255, 0.90);\n"
    "  font-size: 10px; font-weight: 600; letter-spacing: 0.035em;\n"
    "  margin-top: 6px; padding: 4px 9px 4px 8px;\n"
    "  background: rgba(var(--luna-accent-rgb), 0.10);\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.20);\n"
    "  border-radius: 999px;\n"
    "  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.10);\n"
    "}\n"
    ".about_ver_dot {\n"
    "  width: 5px; height: 5px; flex: 0 0 5px;\n"
    "  border-radius: 50%;\n"
    "  background: var(--luna-gold);\n"
    "  box-shadow: none;\n"
    "}\n"
    "#about_sep { width: 100%; height: 1px; background: var(--dialog-divider); margin: 16px 0 12px; }\n"
    "\n"
    "/* Spec grid: single-column stat cards, macOS \"About This Mac\" style */\n"
    "#about_grid { width: 100%; display: grid; grid-template-columns: 1fr; gap: 6px; }\n"
    ".about_spec {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 8px;\n"
    "  padding: 9px 10px;\n"
    "  border-radius: var(--radius-sm);\n"
    "  background: var(--about-card);\n"
    "  border: 1px solid var(--about-border);\n"
    "  box-shadow: none;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".about_spec:hover { background: var(--about-card-hover); border-color: rgba(var(--luna-accent-rgb), 0.36); transform: none; }\n"
    ".spec_icon {\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  width: 26px; height: 26px; flex: 0 0 26px;\n"
    "  border-radius: 7px;\n"
    "  font-size: 12px;\n"
    "  background: rgba(var(--luna-accent-rgb), 0.18);\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.22);\n"
    "}\n"
    ".spec_text { display: flex; flex-direction: column; gap: 2px; min-width: 0; }\n"
    ".spec_label { font-size: 9px; font-weight: 700; letter-spacing: 0.045em; text-transform: uppercase; color: var(--luna-text-muted); }\n"
    ".spec_value { font-size: 11px; font-weight: 600; letter-spacing: 0.005em; color: var(--luna-text-dim); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    "\n"
    "/* ── Settings sheet ── */\n"
    "#settings_sheet.sheet_box {\n"
    "  left: calc(50% - 310px); top: calc(42% - 280px);\n"
    "  width: 620px; height: 560px;\n"
    "  display: flex; flex-direction: column;\n"
    "  padding: 0;\n"
    "}\n"
    "#settings_title {\n"
    "  font-family: var(--display-font);\n"
    "  color: #ffffff; text-align: center;\n"
    "  font-size: 13px; font-weight: 600;\n"
    "  height: var(--dialog-titlebar); line-height: var(--dialog-titlebar); flex: 0 0 var(--dialog-titlebar);\n"
    "  border-bottom: 1px solid var(--dialog-divider);\n"
    "}\n"
    "#settings_body {\n"
    "  display: flex; flex-direction: row; flex: 1 1 auto;\n"
    "  min-height: 0; padding: 0; background-color: transparent;\n"
    "}\n"
    "#settings_sidebar {\n"
    "  width: 150px; flex: 0 0 150px;\n"
    "  display: flex; flex-direction: column; gap: 4px;\n"
    "  background: rgba(0, 0, 0, 0.17);\n"
    "  padding: 16px 10px;\n"
    "  border-right: 1px solid var(--dialog-divider);\n"
    "}\n"
    "#settings_content {\n"
    "  flex: 1 1 auto; display: flex; flex-direction: column;\n"
    "  min-width: 0; min-height: 0; padding: 20px 24px;\n"
    "  background-color: transparent; overflow-y: auto;\n"
    "}\n"
    "\n"
    ".panel_heading {\n"
    "  color: var(--luna-accent-2); font-size: 11px; font-weight: 700;\n"
    "  letter-spacing: 0.08em; text-transform: uppercase;\n"
    "  margin-bottom: 14px;\n"
    "}\n"
    ".stab_icon { margin-right: 8px; opacity: 0.85; font-size: 12px; }\n"
    "\n"
    "/* Sidebar Tabs */\n"
    ".stab {\n"
    "  width: 100%; height: 34px; text-align: left;\n"
    "  color: var(--luna-text-dim); font-size: 13px; font-weight: 500;\n"
    "  padding: 0 12px; border-radius: var(--radius-sm); cursor: pointer;\n"
    "  background-color: transparent; border: 1px solid transparent;\n"
    "  display: flex; align-items: center;\n"
    "  white-space: nowrap;\n"
    "  transition: color var(--dur-fast) var(--ease-out), background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".stab:hover { color: #ffffff; background-color: rgba(255, 255, 255, 0.08); }\n"
    ".stab:focus-visible { outline: 3px solid var(--luna-accent); outline-offset: 2px; }\n"
    ".stab:active { transform: translateY(1px); }\n"
    ".stab.disabled { opacity: 0.45; cursor: not-allowed; }\n"
    ".stab.loading { opacity: 0.72; }\n"
    ".stab.error { border-color: var(--skin-error); }\n"
    ".stab.success { border-color: var(--luna-accent); }\n"
    ".stab.active {\n"
    "  background: linear-gradient(120deg, rgba(var(--luna-accent-rgb), 0.35), rgba(var(--luna-gold-rgb), 0.18));\n"
    "  color: #ffffff; font-weight: 600;\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.45);\n"
    "  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);\n"
    "}\n"
    "\n"
    "/* Pref rows & inputs */\n"
    "#settings_panel_apps { flex: 1 1 auto; display: flex; flex-direction: column; gap: 8px; }\n"
    ".pref_row { display: flex; flex-direction: row; align-items: center; gap: 14px; height: 36px; flex: 0 0 36px; }\n"
    ".pref_label { width: 88px; flex: 0 0 88px; color: var(--luna-text-dim); font-size: 12.5px; font-weight: 500; text-align: right; }\n"
    ".pref_input {\n"
    "  flex: 1 1 auto; height: 32px;\n"
    "  background-color: rgba(0, 0, 0, 0.25);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.14);\n"
    "  border-radius: var(--radius-sm); color: #ffffff; font-size: 12.5px; padding: 0 12px;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".pref_input:hover { border-color: rgba(255, 255, 255, 0.28); }\n"
    ".pref_input:focus { outline: none; border-color: var(--luna-accent); box-shadow: 0 0 0 3px rgba(var(--luna-accent-rgb), 0.25); }\n"
    ".dock_pref { flex: 0 0 38px; cursor: pointer; }\n"
    ".dock_pref:focus-visible { outline: 3px solid var(--luna-accent); outline-offset: 2px; border-radius: 12px; }\n"
    "\n"
    "/* Display panel elements */\n"
    "#settings_panel_disp { flex: 1 1 auto; display: flex; flex-direction: column; gap: 4px; }\n"
    "#settings_panel_language { flex: 1 1 auto; display: flex; flex-direction: column; gap: 8px; }\n"
    "#settings_panel_keyboard { flex: 1 1 auto; display: flex; flex-direction: column; gap: 8px; }\n"
    "#settings_panel_sound { flex: 1 1 auto; display: flex; flex-direction: column; gap: 8px; }\n"
    "#settings_panel_wm { flex: 1 1 auto; display: flex; flex-direction: column; gap: 6px; }\n"
    "#btn_open_alsamixer { width: auto; min-width: 140px; margin-left: auto; }\n"
    "#audio_backend_status, #bright_backend_status { margin-top: 4px; }\n"
    ".pref_section { color: var(--luna-text-dim); font-size: 11.5px; font-weight: 600; margin: 16px 0 8px 0; }\n"
    "\n"
    ".shortcut_row {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 12px;\n"
    "  width: 100%; min-height: 52px; padding: 8px 12px;\n"
    "  border: 1px solid rgba(255, 255, 255, 0.10);\n"
    "  border-radius: var(--radius-sm);\n"
    "  background-color: rgba(0, 0, 0, 0.16);\n"
    "  cursor: pointer;\n"
    "}\n"
    ".shortcut_row:hover { background-color: rgba(255, 255, 255, 0.06); border-color: rgba(255, 255, 255, 0.18); }\n"
    ".shortcut_row:focus-visible { outline: 3px solid var(--luna-accent); outline-offset: 2px; }\n"
    ".shortcut_row.capturing {\n"
    "  border-color: var(--luna-accent);\n"
    "  box-shadow: 0 0 0 3px rgba(var(--luna-accent-rgb), 0.22);\n"
    "  background-color: rgba(var(--luna-accent-rgb), 0.12);\n"
    "}\n"
    ".shortcut_text { flex: 1 1 auto; min-width: 0; display: flex; flex-direction: column; gap: 2px; }\n"
    ".shortcut_name { color: #ffffff; font-size: 13px; font-weight: 600; }\n"
    ".shortcut_desc { color: var(--luna-text-muted); font-size: 11px; }\n"
    ".shortcut_key {\n"
    "  flex: 0 0 auto; min-width: 92px; height: 28px; padding: 0 10px;\n"
    "  border-radius: 8px; background-color: rgba(255, 255, 255, 0.10);\n"
    "  color: #ffffff; font-size: 12px; font-weight: 700;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  letter-spacing: 0.02em;\n"
    "}\n"
    ".shortcut_row.capturing .shortcut_key { background-color: rgba(var(--luna-accent-rgb), 0.35); }\n"
    "\n"
    ".scale_pref { display: flex; flex-direction: column; gap: 4px; margin: 4px 0 10px 0; }\n"
    ".scale_pref .pref_section { margin: 10px 0 0 0; }\n"
    ".scale_pref_head { display: flex; flex-direction: row; align-items: baseline; justify-content: space-between; gap: 12px; }\n"
    ".scale_val { color: #ffffff; font-size: 12.5px; font-weight: 700; min-width: 48px; text-align: right; }\n"
    ".scale_track { margin: 4px 0 2px 0; }\n"
    "\n"
    "/* Hallmark · macrostructure: Catalogue · tone: quiet-utilitarian · anchor hue: violet\n"
    " * component: skin picker · states: default · hover · focus · active · disabled · loading · error · success\n"
    " */\n"
    "#skin_cards {\n"
    "  display: flex; flex-direction: row; flex-wrap: wrap;\n"
    "  gap: 8px; width: 100%; margin-bottom: 14px;\n"
    "}\n"
    ".skin_card {\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 10px;\n"
    "  width: 192px; height: 52px; flex: 0 0 192px;\n"
    "  padding: 6px 8px; border: 1px solid var(--dialog-divider);\n"
    "  border-radius: var(--radius-sm); background-color: var(--skin-card);\n"
    "  color: var(--luna-text); cursor: pointer;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".skin_card:hover { background-color: var(--skin-card-hover); }\n"
    ".skin_card:focus-visible { outline: 3px solid var(--luna-accent); outline-offset: 2px; }\n"
    ".skin_card:active { transform: translateY(1px); }\n"
    ".skin_card.disabled { opacity: 0.5; cursor: not-allowed; }\n"
    ".skin_card.loading { opacity: 0.72; }\n"
    ".skin_card.error { border-color: var(--skin-error); }\n"
    ".skin_card.success, .skin_card.selected {\n"
    "  border-color: var(--luna-accent);\n"
    "  background-color: rgba(var(--luna-accent-rgb), 0.14);\n"
    "}\n"
    ".skin_preview {\n"
    "  width: 40px; height: 38px; flex: 0 0 40px;\n"
    "  border-radius: 6px; border: 1px solid var(--luna-glass-edge);\n"
    "}\n"
    ".skin_preview_0, .skin_preview_3, .skin_preview_6 { background: linear-gradient(145deg, var(--skin-preview-a), var(--skin-preview-b)); }\n"
    ".skin_preview_1, .skin_preview_4, .skin_preview_7 { background: linear-gradient(145deg, var(--skin-preview-c), var(--skin-preview-d)); }\n"
    ".skin_preview_2, .skin_preview_5 { background: linear-gradient(145deg, var(--skin-preview-e), var(--skin-preview-f)); }\n"
    ".skin_copy { min-width: 0; display: flex; flex-direction: column; gap: 2px; }\n"
    ".skin_name { color: var(--luna-text); font-size: 11.5px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    ".skin_desc { color: var(--luna-text-muted); font-size: 9.5px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    "\n"
    "#wp_thumbs_row { display: flex; flex-direction: row; gap: 12px; height: 60px; margin-bottom: 4px; }\n"
    ".wp_thumb { width: 92px; height: 56px; border-radius: 10px; cursor: pointer; border: 2px solid rgba(255, 255, 255, 0.10); transition: border-color var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out); }\n"
    ".wp_thumb.selected { border-color: var(--luna-accent); box-shadow: 0 0 16px rgba(var(--luna-accent-rgb), 0.40); transform: translateY(-2px); }\n"
    ".wp_thumb:hover { border-color: rgba(255, 255, 255, 0.35); }\n"
    ".wp_thumb:focus-visible { outline: 3px solid var(--luna-accent-2); outline-offset: 2px; }\n"
    ".wp_thumb:active { transform: translateY(1px); }\n"
    ".wp_thumb.disabled { opacity: 0.45; cursor: not-allowed; }\n"
    ".wp_thumb.loading { opacity: 0.72; }\n"
    ".wp_thumb.error { border-color: var(--skin-error); }\n"
    ".wp_thumb.success { border-color: var(--luna-gold); }\n"
    ".wp_t_night  { background: linear-gradient(135deg, #06071a 0%, #2e2472 55%, #833a94 100%); }\n"
    ".wp_t_ocean  { background: linear-gradient(135deg, #000b18 0%, #00326a 55%, #40c8f0 100%); }\n"
    ".wp_t_forest { background: linear-gradient(135deg, #040b04 0%, #163418 55%, #58a84a 100%); }\n"
    ".wp_t_sunset { background: linear-gradient(135deg, #0e0510 0%, #5a1c10 55%, #e87040 100%); }\n"
    ".wp_label_row { display: flex; flex-direction: row; gap: 12px; height: 18px; margin-bottom: 8px; }\n"
    ".wp_lbl { width: 92px; color: var(--luna-text-muted); font-size: 10.5px; font-weight: 500; text-align: center; }\n"
    ".wallpaper_motion {\n"
    "  width: 100%; margin-top: 8px; margin-bottom: 16px;\n"
    "  justify-content: flex-start;\n"
    "}\n"
    ".wallpaper_motion.on {\n"
    "  border-color: var(--luna-accent);\n"
    "  background-color: rgba(var(--luna-accent-rgb), 0.16);\n"
    "  color: var(--luna-text);\n"
    "}\n"
    "\n"
    "#cur_thumbs_row { display: flex; flex-direction: row; gap: 12px; height: 100px; margin-bottom: 6px; }\n"
    ".cur_card {\n"
    "  width: 120px; height: 92px;\n"
    "  display: flex; flex-direction: column; align-items: center; justify-content: center;\n"
    "  gap: 4px; cursor: pointer;\n"
    "  background-color: rgba(255, 255, 255, 0.04);\n"
    "  border: 1.5px solid rgba(255, 255, 255, 0.10);\n"
    "  border-radius: var(--radius-md); padding: 8px;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".cur_card:hover { border-color: rgba(255, 255, 255, 0.30); background-color: rgba(255, 255, 255, 0.08); }\n"
    ".cur_card.selected { border-color: var(--luna-accent); box-shadow: 0 0 16px rgba(var(--luna-accent-rgb), 0.35); background-color: rgba(var(--luna-accent-rgb), 0.12); }\n"
    ".cur_preview { width: 34px; height: 34px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.35); }\n"
    ".cur_p_aero { background: linear-gradient(155deg, #f4f6fa 0%, #d0d6e4 55%, #8a92a8 100%); border: 1px solid rgba(255, 255, 255, 0.4); }\n"
    ".cur_p_miku { background: linear-gradient(145deg, #39c5cf 0%, #1a8a96 45%, #e12885 100%); border: 1px solid rgba(255, 255, 255, 0.3); }\n"
    ".cur_name { color: #ffffff; font-size: 12px; font-weight: 600; text-align: center; }\n"
    ".cur_desc { color: var(--luna-text-muted); font-size: 10px; text-align: center; }\n"
    "\n"
    "#kb_thumbs_row { display: flex; flex-direction: row; flex-wrap: wrap; gap: 10px; margin-bottom: 6px; }\n"
    ".kb_current {\n"
    "  display: block; width: 100%; padding: 10px 12px; margin-bottom: 4px;\n"
    "  border: 1px solid rgba(var(--luna-accent-rgb), 0.30); border-radius: var(--radius-sm);\n"
    "  background-color: rgba(var(--luna-accent-rgb), 0.10);\n"
    "  color: var(--luna-text); font-size: 12px; font-weight: 600;\n"
    "}\n"
    ".kb_card {\n"
    "  width: 136px; height: 58px;\n"
    "  display: flex; flex-direction: column; align-items: flex-start; justify-content: center;\n"
    "  gap: 2px; cursor: pointer;\n"
    "  background-color: rgba(255, 255, 255, 0.04);\n"
    "  border: 1.5px solid rgba(255, 255, 255, 0.10);\n"
    "  border-radius: var(--radius-md); padding: 8px 12px;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".kb_card:hover { border-color: rgba(255, 255, 255, 0.30); background-color: rgba(255, 255, 255, 0.08); }\n"
    ".kb_card:focus-visible { outline: 3px solid rgba(var(--luna-accent-rgb), 0.58); outline-offset: 2px; }\n"
    ".kb_card:active { transform: translateY(1px); }\n"
    ".kb_card.selected { border-color: var(--luna-accent); box-shadow: 0 0 16px rgba(var(--luna-accent-rgb), 0.35); background-color: rgba(var(--luna-accent-rgb), 0.12); }\n"
    ".kb_name { color: #ffffff; font-size: 12px; font-weight: 600; }\n"
    ".kb_desc { color: var(--luna-text-muted); font-size: 10px; }\n"
    ".kb_help { color: var(--luna-text-muted); font-size: 10.5px; line-height: 1.5; margin-top: 2px; }\n"
    "\n"
    "/* Hallmark · component: settings dialog · genre: modern-minimal · theme: Luna Moonlight\n"
    " * states: default · hover · focus · active · disabled · loading · error · success\n"
    " * contrast: pass (40–41) · responsive: desktop-session scope\n"
    " */\n"
    ".option_card_grid {\n"
    "  display: grid; grid-template-columns: repeat(2, minmax(0, 1fr));\n"
    "  gap: 8px; width: 100%; margin-bottom: 8px;\n"
    "}\n"
    ".option_card {\n"
    "  min-width: 0; min-height: 64px;\n"
    "  display: flex; flex-direction: column; justify-content: center; gap: 4px;\n"
    "  padding: 8px 12px; cursor: pointer;\n"
    "  border: 1px solid var(--dialog-divider); border-radius: var(--radius-sm);\n"
    "  background-color: var(--skin-card); color: var(--luna-text);\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), transform var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".option_card:hover { background-color: var(--skin-card-hover); }\n"
    ".option_card:focus-visible { outline: 3px solid var(--luna-accent); outline-offset: 2px; }\n"
    ".option_card:active { transform: translateY(1px); }\n"
    ".option_card.disabled { opacity: 0.45; cursor: not-allowed; }\n"
    ".option_card.loading { opacity: 0.72; }\n"
    ".option_card.error { border-color: var(--skin-error); }\n"
    ".option_card.success, .option_card.selected {\n"
    "  border-color: var(--luna-accent);\n"
    "  background-color: var(--color-settings-selected);\n"
    "}\n"
    ".option_card_name { font-size: 12.5px; font-weight: 650; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    ".option_card_desc { color: var(--luna-text-dim); font-size: 10px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    ".settings_notice {\n"
    "  margin-top: 8px; padding: 8px 12px;\n"
    "  border-left: 2px solid var(--luna-gold);\n"
    "  color: var(--luna-text-dim); font-size: 10.5px; line-height: 1.45;\n"
    "}\n"
    "\n"
    ".pref_hint { color: var(--luna-text-muted); font-size: 11px; margin-bottom: 12px; }\n"
    ".pref_row_full { display: flex; flex-direction: row; margin-top: 4px; height: 36px; }\n"
    ".pref_input_full { flex: 1 1 auto; height: 32px; background-color: rgba(0, 0, 0, 0.25); border: 1px solid rgba(255, 255, 255, 0.14); border-radius: var(--radius-sm); color: #ffffff; font-size: 12.5px; padding: 0 12px; }\n"
    "\n"
    "/* Window settings use compact rows, constant geometry and transform-only state. */\n"
    ".wm_pref {\n"
    "  min-height: 54px; display: flex; flex-direction: row; align-items: center;\n"
    "  gap: 12px; padding: 8px 10px; cursor: pointer;\n"
    "  border: 1px solid var(--dialog-divider); border-radius: var(--radius-sm);\n"
    "  background-color: rgba(255, 255, 255, 0.035);\n"
    "}\n"
    ".wm_pref:hover { background-color: rgba(255, 255, 255, 0.07); }\n"
    ".wm_pref.system_pref { min-height: 56px; gap: 12px; padding: 8px 12px; }\n"
    ".wm_pref_text { flex: 1 1 auto; min-width: 0; display: flex; flex-direction: column; gap: 3px; }\n"
    ".wm_pref_name { color: var(--luna-text); font-size: 12.5px; font-weight: 600; }\n"
    ".wm_pref_desc { color: var(--luna-text-dim); font-size: 10.5px; line-height: 1.3; }\n"
    ".wm_switch {\n"
    "  width: 38px; height: 22px; flex: 0 0 38px; padding: 2px;\n"
    "  border: 1px solid rgba(255, 255, 255, 0.18); border-radius: 11px;\n"
    "  background-color: rgba(0, 0, 0, 0.30);\n"
    "}\n"
    ".wm_switch_knob {\n"
    "  width: 16px; height: 16px; border-radius: 8px;\n"
    "  background-color: var(--luna-text-dim);\n"
    "  transition: transform var(--dur-fast) var(--ease-out), background-color var(--dur-fast) var(--ease-out);\n"
    "}\n"
    ".wm_pref.on .wm_switch { background-color: var(--luna-accent-dark); border-color: var(--luna-accent-2); }\n"
    ".wm_pref.on .wm_switch_knob { transform: translateX(16px); background-color: var(--luna-text); }\n"
    ".dock_pref.on .wm_switch { background-color: var(--luna-accent-dark); border-color: var(--luna-accent-2); }\n"
    ".dock_pref.on .wm_switch_knob { transform: translateX(16px); background-color: var(--luna-text); }\n"
    ".wm_pref:active { background-color: rgba(var(--luna-accent-rgb), 0.10); }\n"
    ".wm_pref.disabled, .wm_choice.disabled { opacity: 0.45; cursor: not-allowed; }\n"
    ".wm_pref.loading, .wm_choice.loading { opacity: 0.72; }\n"
    ".wm_pref.error, .wm_choice.error { border-color: var(--skin-error); }\n"
    ".wm_pref.success, .wm_choice.success { border-color: var(--luna-accent); }\n"
    ".wm_pref:focus-visible, .wm_choice:focus-visible { outline: 3px solid rgba(var(--luna-accent-rgb), 0.58); outline-offset: 2px; }\n"
    ".wm_choice_row { display: flex; flex-direction: row; gap: 8px; margin-bottom: 4px; }\n"
    ".wm_choice {\n"
    "  height: 44px; min-width: 92px; display: flex; align-items: center; justify-content: center;\n"
    "  padding: 0 12px; white-space: nowrap; cursor: pointer;\n"
    "  border: 1px solid var(--dialog-divider); border-radius: var(--radius-sm);\n"
    "  background-color: rgba(255, 255, 255, 0.035);\n"
    "  color: var(--luna-text-dim); font-size: 11.5px; font-weight: 600;\n"
    "}\n"
    ".wm_choice:hover { background-color: rgba(255, 255, 255, 0.08); color: var(--luna-text); }\n"
    ".wm_choice:active { transform: translateY(1px); }\n"
    ".wm_choice.selected { border-color: var(--luna-accent); background-color: rgba(var(--luna-accent-rgb), 0.16); color: var(--luna-text); }\n"
    "\n"
    "/* ── Dialog & Action Buttons ── */\n"
    ".dlg_btn {\n"
    "  display: inline-flex; align-items: center; justify-content: center;\n"
    "  height: 30px; min-width: 78px; padding: 0 14px;\n"
    "  border-radius: 7px;\n"
    "  background: rgba(255, 255, 255, 0.12);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.16);\n"
    "  box-shadow: inset 0 1px rgba(255, 255, 255, 0.09);\n"
    "  color: var(--luna-text); font-family: var(--body-font);\n"
    "  font-size: 13px; font-weight: 500;\n"
    "  cursor: pointer; user-select: none;\n"
    "  transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out), transform 100ms var(--ease-out);\n"
    "}\n"
    ".dlg_btn:hover {\n"
    "  background: rgba(255, 255, 255, 0.20);\n"
    "  border-color: rgba(255, 255, 255, 0.25);\n"
    "  color: #ffffff;\n"
    "}\n"
    ".dlg_btn:active { transform: translateY(1px); }\n"
    ".dlg_btn:focus-visible {\n"
    "  outline: 3px solid rgba(var(--luna-accent-rgb), 0.58);\n"
    "  outline-offset: 2px;\n"
    "}\n"
    ".dlg_btn:disabled {\n"
    "  opacity: 0.45;\n"
    "  cursor: default;\n"
    "  box-shadow: none;\n"
    "  transform: none;\n"
    "}\n"
    "\n"
    ".dlg_btn.primary {\n"
    "  background: linear-gradient(180deg, #a898ff, var(--luna-accent));\n"
    "  border-color: rgba(222, 217, 255, 0.36);\n"
    "  color: #ffffff;\n"
    "  box-shadow: inset 0 1px rgba(255, 255, 255, 0.30), 0 1px 4px rgba(0, 0, 0, 0.28);\n"
    "}\n"
    ".dlg_btn.primary:hover {\n"
    "  background: linear-gradient(180deg, #b7abff, #7967ed);\n"
    "  box-shadow: 0 6px 22px rgba(var(--luna-accent-rgb), 0.55);\n"
    "  transform: none;\n"
    "}\n"
    ".dlg_btn.danger {\n"
    "  background: linear-gradient(180deg, #ff625b, #e13832);\n"
    "  border-color: rgba(255, 202, 199, 0.35);\n"
    "  color: #ffffff;\n"
    "  box-shadow: inset 0 1px rgba(255, 255, 255, 0.25), 0 1px 4px rgba(0, 0, 0, 0.28);\n"
    "}\n"
    ".dlg_btn.danger:hover {\n"
    "  background: linear-gradient(180deg, #ff716a, #e8463f);\n"
    "  box-shadow: 0 6px 22px rgba(230, 40, 30, 0.55);\n"
    "  transform: none;\n"
    "}\n"
    "\n"
    "#confirm_cancel, #confirm_ok {\n"
    "  display: flex;\n"
    "  width: 112px; height: 44px; min-width: 112px;\n"
    "  flex: 0 0 112px;\n"
    "}\n"
    "\n"
    "/* ── Launchpad ── */\n"
    "#launchpad {\n"
    "  position: absolute; inset: 0;\n"
    "  background-color: rgba(6, 7, 18, 0.76);\n"
    "  backdrop-filter: blur(40px) saturate(1.6);\n"
    "  -webkit-backdrop-filter: blur(40px) saturate(1.6);\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  padding-top: 48px; padding-bottom: 16px; z-index: 700;\n"
    "  overflow: hidden;\n"
    "}\n"
    "#lp_search {\n"
    "  width: 280px; height: 36px; flex: 0 0 36px;\n"
    "  background-color: rgba(255, 255, 255, 0.12);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.18);\n"
    "  border-radius: var(--radius-md); color: #ffffff; font-size: 13.5px; text-align: center;\n"
    "  padding: 0 16px; transition: background-color var(--dur-fast) var(--ease-out), border-color var(--dur-fast) var(--ease-out);\n"
    "}\n"
    "#lp_search:focus { outline: none; border-color: var(--luna-accent); box-shadow: 0 0 0 4px rgba(var(--luna-accent-rgb), 0.20); background-color: rgba(255, 255, 255, 0.18); }\n"
    "#lp_grid {\n"
    "  width: 820px; max-width: 94%;\n"
    "  flex: 1 1 auto; min-height: 0;\n"
    "  display: flex; flex-direction: row; flex-wrap: wrap; justify-content: center;\n"
    "  align-content: flex-start; gap: 28px;\n"
    "  margin-top: 32px; padding: 4px 8px 24px;\n"
    "  overflow-x: hidden; overflow-y: auto;\n"
    "  scrollbar-width: thin;\n"
    "}\n"
    ".lp_app { width: 110px; display: flex; flex-direction: column; align-items: center; gap: 10px; cursor: pointer; }\n"
    ".lp_app:hover .lp_icon { transform: translateY(-4px) scale(1.05); box-shadow: 0 12px 28px rgba(0, 0, 0, 0.32), 0 0 0 2px rgba(var(--luna-accent-rgb), 0.50); }\n"
    ".lp_icon { width: 72px; height: 72px; border-radius: 20px; color: #ffffff; font-size: 28px; text-align: center; padding-top: 20px; box-shadow: 0 6px 16px rgba(0, 0, 0, 0.28); transition: transform var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out); }\n"
    ".lp_label { width: 110px; color: var(--luna-text); font-size: 12.5px; font-weight: 500; text-align: center; }\n"
    "#lp_hint  { color: var(--luna-text-muted); font-size: 12px; margin-top: 12px; flex: 0 0 auto; }\n"
    "\n"
    "/* ── Notification toast ── */\n"
    "#toast {\n"
    "  position: absolute; right: 16px; top: 44px;\n"
    "  width: 350px; height: auto; min-height: 76px;\n"
    "  background: linear-gradient(165deg, rgba(26, 28, 54, 0.88) 0%, rgba(16, 17, 36, 0.92) 100%);\n"
    "  backdrop-filter: blur(28px) saturate(1.6);\n"
    "  -webkit-backdrop-filter: blur(28px) saturate(1.6);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.16);\n"
    "  border-radius: var(--radius-lg);\n"
    "  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.28), inset 0 1px 0 rgba(255, 255, 255, 0.10);\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 14px;\n"
    "  padding: 14px 16px; z-index: 600;\n"
    "}\n"
    "#toast_icon { width: 44px; height: 44px; border-radius: 14px; flex: 0 0 44px; background: linear-gradient(145deg, var(--luna-accent), var(--luna-accent-dark)); color: #ffffff; font-size: 22px; display: flex; align-items: center; justify-content: center; }\n"
    "#toast_body  { flex: 1 1 auto; }\n"
    "#toast_title { color: #ffffff; font-size: 13.5px; font-weight: 600; }\n"
    "#toast_msg   { color: var(--luna-text-dim); font-size: 12px; margin-top: 2px; }\n"
    "#toast_close { width: 22px; height: 22px; flex: 0 0 22px; border-radius: 50%; background-color: rgba(255, 255, 255, 0.08); color: var(--luna-text-dim); font-size: 13px; display: flex; align-items: center; justify-content: center; cursor: pointer; transition: background-color var(--dur-fast) var(--ease-out); }\n"
    "#toast_close:hover { background-color: rgba(255, 255, 255, 0.20); color: #ffffff; }\n"
    "\n"
    "/* ── Dock ── */\n"
    "#dock {\n"
    "  position: absolute; bottom: 14px; left: 50%;\n"
    "  margin-left: -271px;\n"
    "  width: 542px; height: 82px;\n"
    "  background: linear-gradient(165deg, rgba(22, 24, 48, 0.72) 0%, rgba(12, 13, 28, 0.82) 100%);\n"
    "  backdrop-filter: blur(36px) saturate(1.8);\n"
    "  -webkit-backdrop-filter: blur(36px) saturate(1.8);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.20);\n"
    "  border-radius: 28px;\n"
    "  box-shadow: 0 16px 40px rgba(0, 0, 0, 0.30), inset 0 1px 0 rgba(255, 255, 255, 0.18);\n"
    "  display: flex; flex-direction: row; align-items: center; gap: 10px;\n"
    "  padding: 8px 14px; z-index: 450;\n"
    "}\n"
    "#dock.dock_apps_0 { width: 158px; margin-left: -79px; }\n"
    "#dock.dock_apps_1 { width: 222px; margin-left: -111px; }\n"
    "#dock.dock_apps_2 { width: 286px; margin-left: -143px; }\n"
    "#dock.dock_apps_3 { width: 350px; margin-left: -175px; }\n"
    "#dock.dock_apps_4 { width: 414px; margin-left: -207px; }\n"
    "#dock.dock_apps_5 { width: 478px; margin-left: -239px; }\n"
    "#dock.dock_apps_6 { width: 542px; margin-left: -271px; }\n"
    ".dock_item { position: relative; width: 54px; height: 66px; flex: 0 0 54px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 4px; cursor: pointer; outline: 2px solid transparent; outline-offset: 2px; border-radius: 17px; }\n"
    ".dock_item:focus-visible { outline-color: var(--luna-gold); }\n"
    "/* Dock motion is stylesheet-only (no per-frame C interpolation). */\n"
    "#dock.dock_animated .dock_item:hover .dock_icon,\n"
    "#dock.dock_animated .dock_item:focus-visible .dock_icon {\n"
    "  transform: translateY(-8px) scale(1.28);\n"
    "  box-shadow: 0 10px 24px rgba(0, 0, 0, 0.28), 0 0 0 2px rgba(var(--luna-accent-rgb), 0.45), 0 0 24px rgba(var(--luna-gold-rgb), 0.25);\n"
    "}\n"
    "#dock.dock_animated .dock_item:active .dock_icon {\n"
    "  transform: translateY(-2px) scale(1.12);\n"
    "}\n"
    ".dock_icon {\n"
    "  width: 52px; height: 52px; border-radius: 15px; color: #ffffff; font-size: 20px;\n"
    "  text-align: center; padding-top: 14px; box-shadow: 0 5px 14px rgba(0, 0, 0, 0.26);\n"
    "  transition: transform var(--dur-short) var(--ease-out);\n"
    "}\n"
    ".dock_dot { width: 4px; height: 4px; border-radius: 50%; background-color: var(--luna-gold); box-shadow: 0 0 6px rgba(var(--luna-gold-rgb), 0.90); transition: opacity var(--dur-fast) var(--ease-out); }\n"
    ".dock_dot.spacer { background-color: transparent; box-shadow: none; }\n"
    ".dock_label { position: absolute; left: 0; bottom: 0; width: 54px; height: 10px; color: var(--luna-text); font-size: 8.5px; font-weight: 600; line-height: 10px; text-align: center; opacity: 0; pointer-events: none; transition: opacity var(--dur-fast) var(--ease-out); }\n"
    ".dock_item:hover .dock_dot,\n"
    ".dock_item:focus-visible .dock_dot { opacity: 0; }\n"
    ".dock_item:hover .dock_label,\n"
    ".dock_item:focus-visible .dock_label { opacity: 1; }\n"
    ".dock_sep { width: 1px; flex: 0 0 1px; height: 54px; background: linear-gradient(180deg, transparent, rgba(255, 255, 255, 0.22), transparent); }\n"
    "\n"
    "/* App Gradients */\n"
    ".g_files     { background: linear-gradient(145deg, #6cd4ff, #0a6fe8); }\n"
    ".g_launchpad { background: linear-gradient(145deg, #e2e6f2, #a6b0c8); color: #283456; }\n"
    ".g_terminal  { background: linear-gradient(145deg, #1b1f30, #08090f); color: #38e05a; font-size: 18px; padding-top: 15px; }\n"
    ".g_browser   { background: linear-gradient(145deg, #3ee0d8, #5a6ef2); }\n"
    ".g_editor    { background: linear-gradient(145deg, #ffab2e, #ffd83e); color: #4a2c00; }\n"
    ".g_music     { background: linear-gradient(145deg, #ff6d8e, #c81a68); }\n"
    ".g_settings  { background: linear-gradient(145deg, #b8c0d4, #747e96); }\n"
    ".g_trash     { background: linear-gradient(145deg, #d4dcec, #8a94ac); color: #343e58; }\n"
    ".g_demo      { background: linear-gradient(145deg, #bda6ff, #8248f4); font-size: 22px; padding-top: 22px; }\n"
    ".g_hello     { background: linear-gradient(145deg, #3ee6a8, #0dcf94); color: #063824; font-size: 24px; padding-top: 20px; }\n"
    "\n"
    "/* ── Alt+Tab Switcher ── */\n"
    ".switcher_overlay {\n"
    "  position: absolute; inset: 0;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  background-color: rgba(8, 10, 24, 0.35);\n"
    "  z-index: 900; pointer-events: none;\n"
    "}\n"
    "#switcher_strip {\n"
    "  display: flex; flex-direction: row; flex-wrap: wrap;\n"
    "  align-items: stretch; justify-content: center; gap: 12px;\n"
    "  padding: 18px 20px;\n"
    "  background: linear-gradient(165deg, rgba(22, 24, 48, 0.88) 0%, rgba(12, 13, 28, 0.94) 100%);\n"
    "  backdrop-filter: blur(32px) saturate(1.7);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.18);\n"
    "  border-radius: var(--radius-xl);\n"
    "  box-shadow: var(--shadow-dialog);\n"
    "  max-width: 92%;\n"
    "}\n"
    ".switcher_item {\n"
    "  min-width: 120px; max-width: 180px;\n"
    "  padding: 14px 14px 12px;\n"
    "  border-radius: var(--radius-md);\n"
    "  background-color: rgba(255, 255, 255, 0.05);\n"
    "  border: 1px solid rgba(255, 255, 255, 0.08);\n"
    "  color: #ffffff;\n"
    "}\n"
    ".switcher_item.active {\n"
    "  background-color: rgba(var(--luna-accent-rgb), 0.32);\n"
    "  border-color: rgba(var(--luna-accent-rgb), 0.60);\n"
    "  box-shadow: 0 0 0 1px rgba(var(--luna-gold-rgb), 0.30), 0 10px 28px rgba(0, 0, 0, 0.40);\n"
    "}\n"
    ".sw_app {\n"
    "  font-size: 11px; letter-spacing: 0.04em; text-transform: uppercase;\n"
    "  opacity: 0.65; margin-bottom: 6px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "}\n"
    ".sw_title {\n"
    "  font-size: 14px; font-weight: 600; line-height: 1.25;\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "}\n"
    "\n"
    "/* Compact icon-only status items: labels were removed from Wi-Fi/AC, so do\n"
    " * not retain their old text-sized minimum hit boxes. */\n"
    "#mb_wifi { width: 30px; min-width: 30px; padding-left: 5px; padding-right: 5px; }\n"
    "#mb_bat.icon_only { width: 30px; min-width: 30px; padding-left: 5px; padding-right: 5px; }\n"
    "\n"
    "\n"
    "/* Luna shell UX refinements: notifications, tray tips, Email app. */\n"
    ".g_email { background: linear-gradient(145deg, #71b7ff, #5268df); }\n"
    "\n"
    ".notify_card {\n"
    "  display: flex; flex-direction: column; gap: 3px; min-width: 0;\n"
    "  padding: 8px 10px; margin: 3px 0; border-radius: 8px;\n"
    "  background-color: rgba(255, 255, 255, 0.055);\n"
    "}\n"
    ".notify_meta { display: flex; flex-direction: row; align-items: center; gap: 8px; min-width: 0; }\n"
    ".notify_when { flex: 0 0 auto; font-size: 10px; line-height: 14px; opacity: 0.58; white-space: nowrap; }\n"
    ".notify_title {\n"
    "  flex: 1 1 auto; min-width: 0; font-size: 12px; font-weight: 700; line-height: 15px;\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "}\n"
    ".notify_message {\n"
    "  display: block; min-width: 0; font-size: 11px; line-height: 15px; opacity: 0.78;\n"
    "  white-space: normal; overflow-wrap: anywhere;\n"
    "}\n"
    ".notify_legacy { display: none; }\n"
    "\n"
    ".tray_item { position: relative; }\n"
    ".tray_tip {\n"
    "  position: absolute; top: 3px; right: 28px; min-width: 72px; max-width: 260px;\n"
    "  padding: 5px 8px; border-radius: 6px; background-color: rgba(17, 18, 28, 0.94);\n"
    "  color: rgba(255, 255, 255, 0.96); font-size: 11px; line-height: 14px;\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "  opacity: 0; pointer-events: none; z-index: 1200;\n"
    "  transition: opacity 120ms ease-out;\n"
    "}\n"
    ".tray_item.tip_open .tray_tip { opacity: 1; }\n"
